### ISSUE TITLE
Attempting to build image from Docker file, COPY line gives an error

### ISSUE THREAD

**Issue by jakubLangr** [jupyter/docker-stacks#103]
I managed to run the image all-spark-notebook and was quite happy with it, but I wanted to make some custom modifications, so I tried modifying the docker file on the same machine and this is what happened:

I have the following error when trying to build the docker image from scratch:
`Step 22 : COPY kernel.json /opt/conda/share/jupyter/kernels/scala/
stat kernel.json: no such file or directory` 

I have ssh'ed into the machine at the prior step and did:
`find . -type f -name 'kernel.json'
find: `./etc/ssl/private': Permission denied
./opt/conda/share/jupyter/kernels/ir/kernel.json
./opt/conda/lib/R/library/IRkernel/kernelspec/kernel.json
./opt/conda/pkgs/r-irkernel-0.5-r3.2.2_1/lib/R/library/IRkernel/kernelspec/kernel.json
./opt/conda/pkgs/r-irkernel-0.5-r3.2.2_1/share/jupyter/kernels/ir/kernel.json
find: `./var/cache/ldconfig': Permission denied
find: `./root': Permission denied
find: `./proc/tty/driver': Permission denied`

So there is some `kernel.json` files there, but (a) I am not sure if that is the intended one and if so where is the problem--i.e. is the workdir the wrong folder or is the file in the wrong place?

Oh, just to make this clear, the Dockerfile was __completely unmodified until the very end__, so I think it should be reproducible.

Thanks!

**Comment by parente** [comment]
Have you cloned this repository? The all-spark-notebook folder has a kernel.json in it that has to be in the same folder as the Dockerfile (see https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook). If you grabbed the Dockerfile alone, it won't build because kernel.json is missing in the build environment, not in the image.

And FWIW, if you plan to only append new lines to the existing Dockerfile, you're better off starting from the existing image instead of rebuilding it:

```dockerfile
FROM jupyter/all-spark-notebook

USER root
# stuff you want to add here
USER jovyan
# stuff you want to add here
```

```bash
docker build -t my/all-spark-notebook .
```

**Comment by jakubLangr** [comment]
Thank you! That was the problem, the kernel.json was not in the repo. Also thank you so much for the helpful tip!

**Comment by parente** [comment]
You're welcome. Glad it was a simple fix. :balloon:
