### ISSUE TITLE
on upyter/datascience-notebook:latest the ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'

### ISSUE THREAD

**Issue by BothOfUsTogether2** [jupyter/docker-stacks#1051]
I read all the docs, many issues but it's all for nothing, i literally tried to reinstall like 4 times and comes up with 3 hours doing nothing.

I tried every command... i dont understand why do we have python 2.7 if we just use python3. it's all mixe with pip and conda all fucked up and can't install this shit nbtextensions. i am very thankful for this project but i dont know what to do to fix this issue

**Comment by romainx** [comment]
Hello,

If you have read all the doc, you should also take some additional time to read the [Project Jupyter Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md#project-jupyter-code-of-conduct). It should make the exchanges more pleasant 😄.

If you have find so many issues in the doc please take the time to fix them and submit a PR, it will help other users.

Then, I far as I know, Python `2.7` is not installed in Jupyter images. If you have any evidence of that, please give me the information and we will do something to remove it since, you're right, it's not necessary.

Last, but I'm not sure since it's not specified clearly in your issue. But please have a look to what is done in `scipy-notebook` regarding `nb_extensions`. It could help.

https://github.com/jupyter/docker-stacks/blob/dc9744740e128ad7ca7c235d5f54791883c2ea69/scipy-notebook/Dockerfile#L48-L50

Best

**Comment by BothOfUsTogether2** [comment]
thank you but i give up and just install jupyter without docker...

**Comment by romainx** [comment]
Ok as you want, so I'm closing this issue.

Best.
