### ISSUE TITLE
Is PYTHONPATH effective within notebook ?

### ISSUE THREAD

**Issue by sbgsbc** [jupyter/docker-stacks#1073]
Hi, 

I've modified Dockerfile of jupyter/base-notebook in order to add myself developed python module: mypack. 
```
COPY mypack /home/$NB_USER/code/mypack/
ENV PYTHONPATH=/home/$NB_USER/code/mypack
```

In my notebook 
`!echo $PYTHONPATH`
returns 
`/home/jovyan/code/mypack`

If I print sys.path it's OK too but when I try 
`from mypack import *` 
it returns 
`ModuleNotFoundError: No module named 'mypack'
`
It seems PYTHONPATH is ineffective. How can I access mypack ?

Thanks

**Comment by romainx** [comment]
Hello,

In fact the problem lies into your definition of `PYTHONPATH`. To be able to import the module `mypack` you have to declare in `PYTHONPATH` the directory **containing** `mypack` *and not the `mypack` directory itself*. In the latter Python cannot import the module since it cannot see it.

# Example

Here is a small `custom-notebook` example.
The structure of the `custom-notebook`.

```bash
# __init__.py contains a print saying that the package is loaded
$ tree custom-notebook 
custom-notebook
├── Dockerfile
└── mypack
    └── __init__.py
```

The content of the `Dockerfile`

```Dockerfile
FROM jupyter/base-notebook

COPY mypack /home/$NB_USER/code/mypack/
ENV PYTHONPATH=/home/$NB_USER/code/mypack

CMD ["python", "-c", "import mypack"]
```

The result.
```bash
# The error is reproduced
$ docker run --rm jupyter/custom-notebook 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mypack'
```

Fix, you have to declare the directory included you're package and not the directory of you're package.

```diff
- ENV PYTHONPATH=/home/$NB_USER/code/mypack
+ ENV PYTHONPATH=/home/$NB_USER/code/
```

Build the image and  test the fix, it works.

```bash
$ docker run --rm jupyter/custom-notebook
loading my pack
```

Could you please confirm that it's OK on your side?

Best

**Comment by sbgsbc** [comment]
Thanks again, everything is OK

**Comment by romainx** [comment]
Ok thanks for the update. I'm closing the issue.
Best.
