### ISSUE TITLE
Adding support for plotly / jupyterlab-plotly in the scipy notebook

### ISSUE THREAD

**Issue by nathanrpage97** [jupyter/docker-stacks#1079]
I think it would be a nice addition to add plotly and its jupyterlab-plotly extension to the scipy notebook. ~~There is already precedent for it in [jupyterlab-demo](https://github.com/jupyterlab/jupyterlab-demo/blob/268524d006da026ad1a71b37e4e83c1d0f8d0128/tasks.py#L53)~~. It would be another very nice plotting tool with interactivity.

Edit: plotly extension was removed from core demo.

**Comment by romainx** [comment]
Hello @nathanrpage97,

Thanks for the proposal, it makes sense and it's feasible.
However I would like to have the opinion of others users / contributors.

Before deciding we have also to check

- If the plotly licence is compliant [it seems OK](https://github.com/plotly/plotly.py/blob/master/LICENSE.txt)
- Estimate the size of the installation of plotly + the extension for Jupyterlab. The reason is that we try to keep image size as small as possible (`scipy-notebook` is also the base image of other images). So it would be great to have a comparison before / after in terms of image size (see discussions in #1059 as an example)  

An alternative could also be to not install it and write a recipe or a community image to provide plotly on a `scipy-notebook` base.

So if you have any additional information to share please don't hesitate.
Best.

**Comment by nathanrpage97** [comment]
So I modified and built the Dockerfile locally adding plotly and jupyterlab-plotly.

The uncompressed image went from 3.42GB->3.5GB

```
<none>                               <none>              1d3896b25f5b        5 minutes ago       3.5GB
jupyter/scipy-notebook               latest              903c591af249        2 days ago          3.42GB

**Comment by romainx** [comment]
@nathanrpage97 thank you for the additional information.

I confirm `scipy-notebook` is the right place if we want to install plotly since this is where other plotting libraries and widgets are installed.

So we are talking about ~+80 MB uncompressed on `scipy-notebook`, it seems reasonable however I would like to have the opinion on @parente before launching a PR.

@parente are you good to install plotly and its lab extension?

**Comment by maresb** [comment]
I'd be delighted to see Plotly supported here. I currently maintain my own Dockerfile to add Plotly on top of `tensorflow-notebook`. Consequently I have to maintain compatible versions of the JupyterLab extensions `plotlywidget` and `jupyterlab-plotly`, plus any additional Plotly tools one wishes to use (e.g. jupyterlab-chart-editor).

My observations: 

- It requires a little bit of work to test and maintain when new Plotly versions come out, but the Plotly team is usually quite responsive about fixing major bugs on their primary products.

- With Conda there are two channels with plotly packages: `plotly` and `conda-forge`. Historically, I've always used the `plotly` channel, but recently I've noticed some really nasty dependency conflicts which occurred when using the `plotly` channel. After switching to `conda-forge` things generally work flawlessly, even with the latest versions.

I'm happy to shift my private efforts at maintaining Plotly support over to the docker-stacks so that everyone can benefit, although I can't promise any specific commitment.

**Comment by maresb** [comment]
Another very important practical consideration regarding Plotly is that once one starts plotting tens of thousands of points, the JupyterLab interface starts to seriously lag. Consequently, it's good practice to render large plots as images rather than `FigureWidget`s. Unfortunately, supporting rasterization requires running an [Orca server](https://github.com/plotly/orca), which has some complicated dependencies. As a result, I'm using `docker-compose` to run my container alongside Plotly's Docker image for Orca.

**Comment by mathbunnyru** [comment]
@nathanrpage97 @maresb are you still interested in adding plotly?

If I don't get a response, I will probably close this PR, because no one is actually interested in this feature.

**Comment by maresb** [comment]
This should be super easy these days. The recent versions of plotly have a built-in rasterization library called Kaleido which replaces Orca. I think it's simply a matter of adding `plotly` to the conda dependencies.

**Comment by maresb** [comment]
For my workflow, I add `plotly` and `python-kaleido` with `mamba`, and then run the following two lines. I'm not sure whether or not these are still necessary:
```
jupyter labextension install --debug jupyterlab-plotly --no-build
jupyter labextension install --debug plotlywidget --no-build
```

**Comment by mathbunnyru** [comment]
I think, if someone needs plotly, they will just follow instructions and it should be ok, I suppose.
How do you feel about closing this issue?

**Comment by maresb** [comment]
Sure, fine by me!

**Comment by mathbunnyru** [comment]
Ok, thanks, closing then :)
