### ISSUE TITLE
Pandas data frame can only use one CPU core?

### ISSUE THREAD

**Issue by yonghaihung** [jupyter/docker-stacks#1084]
Hi,

Most jobs run in Spark can parallelise its job, utilising multi-core (up to 20 cores on local machine) even using local config. 

However when running some lighter tables or trying to make use of Pandas data frame as a intermediary to output to_csv or to_sql (using SqlAlchemy), the Pandas data frame takes a long time to complete its job and it can only use one CPU core.  

Is this a Pandas limitation or is there an issue with this docker stack?

**Comment by yonghaihung** [comment]
Would also like to know if the above problem like making use of multi-core for pandas.to_sql can be solved by using Dask, e.g. df.map_partitions

**Comment by Bidek56** [comment]
By default, Pandas executes its functions as a single process using a single CPU core.
If you need multi-core execution, please try:

- [Koalas](https://github.com/databricks/koalas)
- [modin[ray]](https://modin.readthedocs.io/en/latest/)
- [Dask](https://github.com/dask/dask)

**Comment by romainx** [comment]
@Bidek56 thanks for your answer.

@yonghaihung, you can also check the official Pandas guide [Scaling to large datasets](https://pandas.pydata.org/pandas-docs/stable/user_guide/scale.html) that mentions dask. Note also that dask is installed in `scipy-notebook` and downstream images so you can give it a try.

If it's Ok for you, we will close this issue since it is more related to pandas than Jupyter Docker images.

Best.

**Comment by yonghaihung** [comment]
Noted with thanks.

I’m ok to close the issue.

**Comment by romainx** [comment]
Thank you 😄
