### ISSUE TITLE
Do we need texlive-fonts-extra in the minimal-notebook?

### ISSUE THREAD

**Issue by LustigePerson** [jupyter/docker-stacks#1129]
Do we really need the `texlive-fonts-extra` package in the [minimal-notebook](https://github.com/jupyter/docker-stacks/blob/ea01ec4d9f5715ab7dd85d4742ad6416c343c8bd/minimal-notebook/Dockerfile#L29)? It is commented to be optional and I guess `nbconvert`does not need it for basic functionality.
The problem is that it really bloats the image:
```bash
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
minimal-notebook-nofonts      latest              9641ee9dd31c        3 minutes ago       1.7GB
minimal-notebook              latest              e23d7794a410        14 minutes ago      3.01GB
```
That's 1.3 GB difference...

Any thoughts on that?

**Comment by romainx** [comment]
Hello,

Good catch I've done the previous work to clean things up on `tex` / `nbconvert` / `pandoc`. In the PR #1013

In [one of my comments](https://github.com/jupyter/docker-stacks/pull/1013#discussion_r379897106 ) I had the same interrogation about the `texlive-fonts-extra` package.
> And the following extra packages is installed, there necessity could be challenged
> 
> * `texlive-fonts-extra`
> 
> [Here](https://tex.stackexchange.com/a/504566) is a great answer on SO explaining the content and the dependencies between those packages.

So I guess is time to go further on this topic since, according to the figures you got, we can make an impressive size reduction on the images 😮. Moreover it will benefit to all images built on top of `minimal-notebook`, so in short all images except `base-notebook`.

Do you mind drafting a PR?
In the meantime, if anyone has a rationale or evidence of using this usage, please tell us.

Many thanks for your contribution.
Best.
