### ISSUE TITLE
Put a monotonically increasing number in the docker image tag

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#113]
It's really hard on Docker Hub to find out the image tag with the git SHA associated with the latest image.  It's also hard to figure out the SHA order without some back and forth between github and dockerhub.

Proposal: Add a monotonically increasing number to the docker image tag on every build like so:

```
jupyter/minimal-notebook:1-0017b56d93c9
jupyter/minimal-notebook:2-39432abcef31
jupyter/minimal-notebook:3-deadbeef1234
# etc.
```

This makes the history of images clearer for humans and retains the git-sha link back to the exact state of the repository when the images were built.

**Comment by jakirkham** [comment]
So, we currently are using SHA only? Would it make sense to start having an explicit semantic or other version with a SHA attached for development? Sorry, I am just trying to get my bearings.

**Comment by parente** [comment]
Brief summary: there's tons of libs in these images with tons of different versioning schemes. There's no way to capture the version of Spark (1.5.1), Notebok (4.1), pandas (0.17.1), matplotlib (1.5.1), etc. all in a succinct Docker image tag. So, instead, the git SHA is used as the Docker image version: it's a pointer back to the state of all of the Dockerfiles that were built. (The full history is in #12 and the high level is documented in the README.)

This issue is about adding one additional bit to that tag for human consumption and to give the image builds a visible ordering.

**Comment by jakirkham** [comment]
> Brief summary: there's tons of libs in these images with tons of different versioning schemes.

Definitely. Though we could somehow note when we have introduced a breaking change where at least one of our dependencies has a breaking change (e.g. matplotlib 1.5.x -> 2.0.0) or we break something ourselves. We could also note when there are no breaking changes, but at least one of our dependencies adds new features (e.g. matplotlib 1.5.x -> 1.6.x). Similarly for when there are no breaking changes or new features, but only bug fixes in our dependencies or our image.

That all being said, this may still be too challenging to pursue because not all dependencies may comply with semantic versioning nor may it be appropriate for all of them to do so. The only reason I suggest it is if we are considering changing the versioning to temporal order maybe we should think a little bit more about what versioning means for the stacks themselves even if we decide this ends up being inappropriate.

> The full history is in #12 and the high level is documented in the README.

I think I saw this before recently. It is coming back to me now. :)

> This issue is about adding one additional bit to that tag for human consumption and to give the image builds a visible ordering.

Sure, the proposal sounds reasonable to me.

Another thought on ordering is we could use the number of commits since the beginning, it may make this easier to autogenerate and build. Then again this number might get quite large. So, the original proposal still sounds fine to me.

**Comment by parente** [comment]
> Though we could somehow note when we have introduced a breaking change where at least one of our dependencies has a breaking change (e.g. matplotlib 1.5.x -> 2.0.0) or we break something ourselves. We could also note when there are no breaking changes, but at least one of our dependencies adds new features (e.g. matplotlib 1.5.x -> 1.6.x). Similarly for when there are no breaking changes or new features, but only bug fixes in our dependencies or our image.

I see what you mean. The challenge is as you noted: we can control for direct dependencies in the Dockerfiles, but we can't capture the exact reason behind second-level dependencies and beyond. That, and we don't exactly pin the version of all dependencies, today. The Dockerfiles assume that the libraries being installed are reasonable actors when it comes to versioning, and allows the patch part of the version number to float freely across builds.

I'm open to alternatives if you can lay out the rules that would be followed.

> Another thought on ordering is we could use the number of commits since the beginning, it may make this easier to autogenerate and build. Then again this number might get quite large. So, the original proposal still sounds fine to me.

If we're sticking with single integer, this is better than starting arbitrarily at 0 or 1.

**Comment by parente** [comment]
Another tactic.

Keep the tags as they are. Set Docker Hub web hooks for each docker-stacks Docker repository. Write a little web hook listener (or find a service). When new tags appear, update a human readable page (wiki page here?) with information about the build (image name, tag name) and  link it back to the github view for the git SHA. Keep updating the page in chronological order, newest builds at the top.

**Comment by parente** [comment]
> It's really hard on Docker Hub to find out the image tag with the git SHA associated with the latest image. 

Small update: Docker Hub's UI seems to be sorting tags by date again.

**Comment by jakirkham** [comment]
So, do you think this is not necessary then?

**Comment by parente** [comment]
I think there's still room for improvement, but it's a bit less pressing. I manually drafted [this build table page on the wiki](https://github.com/jupyter/docker-stacks/wiki/Docker-build-history) last night and was thinking today about writing a little webhook receiver that would simple update it with the metadata you see there (plus a little bit more) on every push to Docker Hub.

**Comment by parente** [comment]
I think with the webhook in place, there's no need to change the versioning scheme. It's pretty easy to tell the tag sequence from the build page.

We might need to improve the info on the page over time, but that's a separate issue.
