### ISSUE TITLE
Create both Spark2 and Spark3 docker images

### ISSUE THREAD

**Issue by robrich** [jupyter/docker-stacks#1131]
All of a sudden the image upgraded from Spark2 to Spark3.  I'm really glad there's a manually created `spark-2` tag or I would be sunk!  But I'm now stranded on an old, unmaintained version.  Oops.

Can we get the Docker Build to build `latest` using Spark3 as it does now, and also get the build to create `spark-2` tagged images as well?

It appears https://github.com/jupyter/docker-stacks/commit/568708d2794fb534a2a4c141796de308685be1f7 is the commit that made the change.  Is it as easy as two jobs, one that passes in `APACHE_SPARK_VERSION=2.4.5` and `HADOOP_VERSION=2.7`?

**Comment by romainx** [comment]
Hello @robrich,

In fact my idea to solve this request, and also to permit to user to use different Spark version is to create a [recipe](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html). But first we need to perform some changes in the `pyspark-notebook` `Dockerfile`. Use arguments (`ARG`), along with their default valuen, to specify which Spark installation to perform

* `apache_spark_version`: The Spark version.
* `hadoop_version`: The Hadoop version.
* `java_version`:  Spark `3.0` can run on Java `8` or `11`, see [Spark documentation](https://spark.apache.org/docs/latest/#downloading).
* `spark_archive_checksum`: The checksum of the Spark archive to install.
* `py4j_version`: The version of the [`py4j`](https://www.py4j.org/) shipped with Spark since its version changes with Spark. Note: we could also find a better (dynamic) way to do it.

With these changes it will be possible to install a different Spark release by overriding some of the arguments at build time.

What is your opinion about this proposal?

Best.

**Comment by robrich** [comment]
I think this sounds perfect.  Then have the Docker Hub build pass in both versions and publish two different tags.  Perhaps `latest` and `2-latest` or similar.

**Comment by robrich** [comment]
I love the versatility to pass in any version, but on Docker hub it appears
there's still only one version. Could the build be adjusted to run twice,
passing in 3.x and 2.x?

**Comment by romainx** [comment]
Hello,

Following the merge of the PR #1145 you can now build your own image with a different Spark version. [This part](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#build-an-image-with-a-different-version-of-spark) of the documentation explains how to do it.
We will not manage several versions in the stack (with different stack) because it's too much work. This project tries to propose the latest versions available and keep all the previous stacks (see [wiki](https://github.com/jupyter/docker-stacks/wiki)) if someone need to use a specific version.

Hope this change will help you.
Best.
