### ISSUE TITLE
Suggestion for new feature in core stacks: batchspawner package

### ISSUE THREAD

**Issue by twrobinson** [jupyter/docker-stacks#1155]
Hi, as per https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/features.html, I would like to suggest the inclusion of batchspawner. Personally, I think that inclusion would make sense in the core stacks, as it is generally applicable (at least for those using JupyterHub with BatchSpawner!), is a lightweight package, and is not scientific software - so not stack dependent. I would be happy to hear feedback from the maintainers. 
The complexity of build would be minimal (one or two lines of code) and increase of image size negligible.  
Thanks in advance for considering this.

**Comment by romainx** [comment]
Hello @twrobinson,

Thank you for this suggestion.
I do not have a good knowledge of [batchspawner ](https://github.com/jupyterhub/batchspawner), but from my understanding it is a spawner like any others. In that case I'm not sure it's a good place to install spawners. As far as I know, spawners have to be installed on JupyterHub side, and the images in this repositories are more intended to be spawned by `DockerSpawner` or `KubeSpawner` than used as a Spawner. 

Maybe I'm wrong. I let other contributors / maintainers give their opinion.
Best.

**Comment by romainx** [comment]
Hello @twrobinson what do you think of my last comment?

Please let us know.

**Comment by twrobinson** [comment]
Hi @romainx, excuse my slow reply - I was waiting to see if other contributors / maintainers had an opinion.

Yes, batchspawner is indeed required on the JupyterHub side. But if you are running your JupyterHub server outside the HPC cluster, then the jupyterlab build on the cluster will also need batchspawner (jupyterhub executes batchspawner-singleuser) in order for them to talk to each other. 

I can see your point about the major use cases being DockerSpawner and KubeSpawner. So, if there is no strong desire from others for batchspawner I think you can probably close this issue.

**Comment by rkdarst** [comment]
@twrobinson is right, it's not strictly needed but this
`batchspawner-singleuser` wrapper would be needed if, for example, a
hub used batchspawner to invoke something on a cluster, that ran in a
docker/singularity container.  It's certainly possible, and with stuff
going towards containers more someone might even be doing it now.

Since batchspawer is very small, I guess it can't hurt.  But,
batchspawner releases are very infrequent almost to the point of the
released version not being highly recommended historically.  We are
going to try to improve that, but still the current release on PyPI is
not usable, and I might recommend waiting to see if releases do come
out more often.  Otherwise, the options are install from git in the
image or expect people to do so themselves...

**Comment by twrobinson** [comment]
Hi @rkdarst  
Thanks for the positive feedback. I saw that you released 1.0 a couple of months ago - is there a reason you haven't published it on pypi?

**Comment by rkdarst** [comment]
There's no particular reason, other than waiting for a maintainer's
time.  I can't do it as I'm not a maintainer.

**Comment by romainx** [comment]
@twrobinson if you agree I'm going to close this feature request because I do not think we will work on it, at least soon.
Is it OK for you?

Thanks

**Comment by twrobinson** [comment]
Yes, I think it is perfectly reasonable to close this request. Thanks!
