### ISSUE TITLE
Cloud minimal interfaces

### ISSUE THREAD

**Issue by jomach** [jupyter/docker-stacks#1179]
Hello everyone, 

I would like to know if it would make sense to add to the base image the python apis for Azure, AWS and gcloud.
Example for azure: 

```
RUN pip install azure-cli==2.11.1 \
azure-storage-blob==12.5.0 \
azure-storage-file-share==12.2.0 \
azure-identity==1.4.0 \
azure-datalake-store==0.0.49 \
azure-keyvault-secrets==4.2.0 \
pandas-profiling==2.9.0
```
 what do you think ?

**Comment by romainx** [comment]
Hello,

Thanks for this suggestion, it could be interesting, however we try to keep the images as small as possible and as much as possible easy to maintain. This is even more the case for the base images (`base-notebook` and `minimal-notebook`) because they are used as upstream images by all the others. These images are agnostic from their environment so I do not think we would like to add.

So I would suggest either to write a [contributed recipe](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html) or to create a [community stack](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html). I think the latter solution is a better choice.

Best.

**Comment by jomach** [comment]
Fair enough
