### ISSUE TITLE
OpenSSH Information Disclosure Vulnerability in jupyter/scipy-notebook:42f4c82a07ff

### ISSUE THREAD

**Issue by JavierHernandezMontes** [jupyter/docker-stacks#1191]
Hi! Thanks for using the Jupyter Docker Stacks.

Please review the following guidance about how to ask questions, contribute changes, or report bugs in the Docker images maintained here.

**What docker image you are using?**

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

 `docker run -it --rm -p 8889:8888jupyter/scipy-notebook:42f4c82a07ff`

**What actually happens?**

The  docker image itself has this security issue:

 105936-OpenSSH Information Disclosure Vulnerability
 Type | Vulnerability
 Published | 11/3/2020, 1:50 PM GMT+1
 Patchable | Yes 
 Cvss 3.0 base score | 7.8
 CVEs | CVE-2020-14145 CVE-2020-15778

According to Qualys analysis

**Comment by romainx** [comment]
Hello,

Those CVE are coming from our base image `ubuntu:focal` and are known in LOW priority with the status Ignored.

* [CVE-2020-14145](https://ubuntu.com/security/CVE-2020-14145)
* [CVE-2020-15778](https://ubuntu.com/security/CVE-2020-15778)

If you want to have those CVE fixed you can ask Ubuntu support or try to rebuild the image from another base image without those vulnerabilities.

So I'm closing the issue because it is an upstream issue that will not be treated at this level.
Best
