### ISSUE TITLE
Code Completion in Notebook not working - Tab not functional

### ISSUE THREAD

**Issue by sandeepmohan** [jupyter/docker-stacks#1215]
**What docker image you are using?**

`jupyter/all-spark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook:latest -v mylocaldir:/HOME/JOVYAN/WORK
`
**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Start an Python Notebook
3. Import in a package. For Example: `import pandas as pd`
4. Go to next cell.
5. Try to read in a csv file `df = pd.read...`

**What do you expect to happen?**

At step 5 above, I would have expected to be able to tab after the `pd.` in order to get be able to access pandas options. 

Expected Behavior better outlined here: https://towardsdatascience.com/jupyter-notebook-autocompletion-f291008c66c 

**What actually happens?**

Literally nothing. The cursor moves ahead by a tab.

**Note:** I am still able to complete the code `pd.read_csv("file", sep=',') but a key capability of the notebook seems stunted.

Thanks in advance.

Sandeep

**Comment by romainx** [comment]
Hello @sandeepmohan,

You're right did not notice it. This is issue is tracked in https://github.com/ipython/ipython/issues/12740. Apparently the root cause is a compatibility problem between `ipython` and `jedi` `1.8.0`. The root cause seems to be https://github.com/davidhalter/jedi/issues/1714.

The workaround is to downgrade the version of `jedi`. You can do it directly in the notebook console and happily use tab again.

```bash
conda install jedi==0.17.2
```

I will check if we can do a kind of fix on our side while waiting for the upstream fix.

Best

**Comment by sandeepmohan** [comment]
Romain,

The fix works. Just updated my stack and I am back in business. Many
Many Thanks!!

--
Sandeep Mohan
sjmohan@gmail.com | (703) 732-3757

**Comment by romainx** [comment]
Note: Here is another way that could be used to fix this issue

```python
c.Completer.use_jedi = False.
```
https://github.com/ipython/ipython/issues/12740#issuecomment-763018119
