### ISSUE TITLE
No permission to access /home/jovyan/work folder

### ISSUE THREAD

**Issue by doglasfc-docker** [jupyter/docker-stacks#1223]
when I use following command:
docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/jovyan/work jupyter/datascience-notebook

I don't have the permission to navigate  /home/jovyan/work folder to create any files in jupyter environment? 

(Since I set the the volume to $PWD, I want to create  a file in $PWD location and see it in /home/jovyan/work of Docker image instance.

Sorry, I'm the docker learner.

**Comment by Bidek56** [comment]
Have you searched prior issues before posting this? Please [see](https://github.com/jupyter/docker-stacks/issues/542) which has references to few solutions.
What OS are you using? WSL2 is known to have permission issues.

**Comment by romainx** [comment]
Hello @doglasfc-docker,

Thanks @Bidek56 for this suggestion. In addition, we have not yet taken the time to do it but we would like to create a troubleshooting page and one of the recurring issue / question is this one. This initiative is described in the issue #1071 (I have just added your suggestion @Bidek56) and there is a section called _Permission denied when mounting local folders_ listing several issues reporting the same problem. So please take the time to look at them to find the right solution at your problem.

I'm closing this issue since I'm pretty sure you will find the solution in those past issues. Feel free to post a new comment in this issue if it's not the case.

Thanks for your understanding.
Best.
