### ISSUE TITLE
Alpine OS base

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#1242]
Is there any plan to investigate using Alpine as the base OS?  With these images, it's not about file size.  It's more about security posture.  It seems starting with Alpine vs. Ubuntu might help some security vulnerabilities that scanners will sometimes highlight with Ubuntu.  

Do we know of a technical limitation that would prevent this?

**Comment by mathbunnyru** [comment]
Actually, this is quite an interesting question 👍 
Disclaimer: I only used alpine for 15 minutes in my life.

Yes, it might be possible to get smaller images and probably more secure images.

But for python packages especially there is a big downside:
https://pythonspeed.com/articles/alpine-docker-python/

The python software didn't work that well on alpine image 1 year ago. Has this changed? (sorry, I'm no expert in alpine, as I said).

Some things to also consider (need investigating):
- package manager is different
- we might rely on some packages already included in ubuntu docker and not set to manual install
- something might not even work under alpine by default
- or you will need to compile some software from scratch
- libc is different (might be a big trouble)
- we will definitely other people images (for all the reasons above)

I can tell you that @romainx makes a lot of efforts to keep ubuntu image up-to-date.
We also do not specify versions of apt binaries and update conda/pip packages quite often.

So, I think, we might have many troubles with alpine image, especially because many people might rely on our Dockerfiles and base their own images on the official ones (I do, for example).

Hope, this answers your question :)

**Comment by romainx** [comment]
Hello @rwmajor2,

To complete what @mathbunnyru said, I would like to highlight that **I'm not sure Alpine is the best alternative**. I've been aware of issues with Alpine running Python. [This very good article][1] gives a good picture of the problem.  And this problem seems to be worst with libraries heavily relying on C and it is mostly the case of the scientific libraries we are using (for example numpy) due to the fact that `glibc` is replaced by `musl` in Alpine distributions.

Best

[1]: https://pythonspeed.com/articles/alpine-docker-python/

**Comment by srggrs** [comment]
Hi,

Seems other people are moving away from alpine + jupyter, see [this repo](https://github.com/nbgallery/jupyter-alpine#repository-status). Hope those info help in the answer.

Cheers,
S

**Comment by rwmajor2** [comment]
Thanks everyone.  This was enough to answer my question.

**Comment by jeffyjefflabs** [comment]
> Seems other people are moving away from alpine + jupyter, see [this repo](https://github.com/nbgallery/jupyter-alpine#repository-status). Hope those info help in the answer.

I didn't notice this issue while it was open - I work on the nbgallery project referenced here, and I'll echo what others in the thread have said.  For a general-purpose project like this one or what we were doing with nbgallery, where users want to be able to pip install any arbitrary package, using Alpine was a constant struggle.  We used it for a couple years before switching over to jupyter/docker-stacks, and it has been **much** smoother.

That said, Alpine can be a good option for more specialized applications where image size is a real constraint and you know up front exactly what packages you will need, and you're willing to do a little legwork to figure out which packages should be installed as Alpine apks and which should be installed via pip.  Binder is a good example - known, fixed dependencies; not sure if they have an image size limit, but I imagine smaller is generally better.  For anyone thinking of going down this road, I've collected a few thoughts and references in our other nbgallery repo [here](https://github.com/nbgallery/docker-images/tree/main/alpine-notebook).
