### ISSUE TITLE
vulnerability detected from texlive-xetex -> libpdfbox-java

### ISSUE THREAD

**Issue by JessicaBarh** [jupyter/docker-stacks#1299]
**What docker image you are using?**

jupyter/datascience-notebook:r-4.0.3

**What complete docker command do you run to launch the container (omitting sensitive values)?**

 `docker run -it --rm -p 8889:8888 jupyter/datascience-notebook:r-4.0.3`

**What steps do you take to reproduce the issue?**

`trivy image --severity CRITICAL jupyter/datascience-notebook:r-4.0.3`

there is a vulnerability in pdfbox which is a installed with texlive-xetex-extra and that is installed [here](https://github.com/jupyter/docker-stacks/blob/20c9b80428d89421e71ce2f0e2b7ef6c2d1762c4/minimal-notebook/Dockerfile#L22) through texlive-xetex (required for nbconvert). There seems to be no support or work being done on the [xetex ](https://github.com/TeX-Live/xetex) side for over a year... are there any ideas for resolving this?

**Comment by romainx** [comment]
@JessicaBarh thanks for the warning, however according to the [documentation](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex) it seems to be the way to install nbconvert with PDF support.

```bash
sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended
```

As you said according to the dependency tree confirm that everything seems Ok regarding our installation.

```bash
apt-cache rdepends --installed libpdfbox-java
# Reverse Depends:
#  texlive-latex-extra

apt-cache rdepends --installed texlive-latex-extra
# Reverse Depends:
#  texlive-xetex
#  texlive-pictures
#  texlive-latex-recommended
#  texlive-latex-base
#  texlive-base
```
I have no idea except creating an issue in the [nbconvert](https://github.com/jupyter/nbconvert) project in order to check if someone know an alternative.

Sorry.

**Comment by mathbunnyru** [comment]
@JessicaBarh I have just run `trivy image --severity CRITICAL jupyter/datascience-notebook` (with latest image) and I don't see `libpdfbox-java` in the list of errors.
Could you please check, that the issue still persists?

**Comment by mathbunnyru** [comment]
Closing this, if the issue still persists, please reopen.
