### ISSUE TITLE
TypeError:an integer is requird(got type bytes). The python version is too high?  

### ISSUE THREAD

**Issue by NaUyLL** [jupyter/docker-stacks#1336]
Now I am using the spark-2.4.5. Then I meet the error. I find the python version is 3.9.x in the container.  This is the reason to cause the error? 
In the pyspark's Dockfile, I find the pyspark-jupyter is based on scipy-jupyter. Scipy-jupyter also has its base container. So how can I build a low-version (or choose a version) python for the spark? Are there any parameters that can be used to control the python version？

**Comment by romainx** [comment]
Hello @NaUyLL,

Exactly you are right. It's an incompatibility between newer versions of Python and older versions of Spark. See [this post](https://stackoverflow.com/questions/61348860/spark-installation-problems-typeerror-an-integer-is-required-got-type-bytes) on SO to get more information.

I'm closing the issue since this problem is not related to our stack.
Best
