### ISSUE TITLE
enable multi core settings in pyspark-notebook

### ISSUE THREAD

**Issue by robomotic** [jupyter/docker-stacks#1369]
**What docker images this feature is applicable to?**

Example: `jupyter/pyspark-notebook`

**What changes do you propose?**

Taking this example:
```

from pyspark.sql import SparkSession

# Spark session & context
spark = SparkSession.builder.master('local').getOrCreate()
sc = spark.sparkContext

# Sum of the first 100 whole numbers
rdd = sc.parallelize(range(100 + 1))
rdd.sum()
# 5050

```

How can I use my 16 logical cores in my host.

I tried:

```

from pyspark.sql import SparkSession

# Spark session & context
spark = SparkSession.builder.master('local[16]').getOrCreate()
sc = spark.sparkContext

# Sum of the first 100 whole numbers
rdd = sc.parallelize(range(100000 + 1))
rdd.sum()
# 5050

```

But only one core in my system is being used.

Are there other settings I should change when the image is being built?

**Comment by romainx** [comment]
Hello,

Local mode is a development tool where all processes are executed inside a single JVM. The number between brackets, in your case `local[16]`, correspond to threads, so it will use 16 threads instead of 16 CPU.

> In this non-distributed multi-threaded runtime environment, Spark spawns all the main execution components in the same single JVM.
> The default parallelism is the number of threads as specified in the <>. This is the only mode where a driver is used for execution (as it acts both as the driver and the only executor).
> -- [source](https://books.japila.pl/apache-spark-internals/local/?h=local)

If you want to use all the CPU one of the simplest way is to setup a [Spark Standalone Cluster][1].
It is often done with several containers acting as spark components (master and workers) and can be setup through a simple docker compose.

Not sure we have something to do in the stack, but maybe it could be interesting to have a recipe showing how to use our Spark images with a standalone Spark cluster.

Best. 


[1]: http://spark.apache.org/docs/latest/spark-standalone.html

**Comment by robomotic** [comment]
Hi there,
thanks for the explanation, I didn't realize those were threads but how can I make sure there are 16 running.
What I did was to open the terminal from jupyter and monitor the Java process that gets created.

When I do this during the execution (takes several minutes to complete):

(base) jovyan@bbf77cee22d7:~$ ps -e -T | grep java
   2476    2476 ?        00:00:00 java
   2476    2498 ?        00:00:02 java

Does it mean is just running on 2 threads instead of the specified 16?

Yes that would be great to have an example for the standalone cluster!

Thanks for the help!

**Comment by romainx** [comment]
Hey,

You can see java thread by using `top -H -p $pid`.
As you can see in this screenshot the setting produces the expected number of executors.
<img width="1349" alt="JupyterLab" src="https://user-images.githubusercontent.com/7131913/122474390-6e3d1000-cfc3-11eb-9981-c07bfa89d60c.png">

Ok for the example, it's a good idea.

Best.

**Comment by robomotic** [comment]
Yes I can confirm I can see those threads too.
Great thanks for he help.
