### ISSUE TITLE
Mounting EFS/NFS to home without root privileges

### ISSUE THREAD

**Issue by droctothorpe** [jupyter/docker-stacks#1394]
Correct me if I'm wrong, but it looks like the [start.sh](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L67) script requires root privileges to mount NFS. 

I understand that it subsequently deescalates, however, we're using JupyterHub to provision notebooks on K8s and we want to provide a custom image field in the options form, but there's no way for us to guarantee deescalation in that context, which is a show-stopper.

Is it possible to mount an EFS volume to the home directory without running the container as root?

**Comment by jlphillipsphd** [comment]
Would nfs-subdir-external-provisioner (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) work for you in this context? I typically use this now instead of direct NFS mounts like I have tried in the past.

This allows containers to mount from anywhere in the cluster (like one wants from NFS), and the provisioner provides a storage class backed by NFS to make it pretty simple to request pvcs for just about anything. I even manage the NFS server which backs the storage class using k8s as well, so no resources outside of the cluster need necessarily be used.

**Comment by droctothorpe** [comment]
We figured out a solution and documented it in this PR: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2538. Closing this issue.
