### ISSUE TITLE
Tags and manifests are created based on amd64 images, but assumed for the arm64 images

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1401]
In #1399 we add let this repo publish arm64 based images rather than the amd64 based images we currently have published.

This issue is meant to represent the problem of doing so without also documenting the version of packages installed etc, which may be different for an arm64 based image compared to an amd64 based image. Also, we only publish manifests based on the amd64 images rather than both, or clarify it is only the manifest of the amd64 based image.

**Comment by mathbunnyru** [comment]
@romainx if you have free time to dig into the most important issues, here is one of them.

This issue comes from the way we build images using `docker buildx` and how we tag them.
This scheme is over complicated and creates tons of problems for both users and maintainers.

What we can and probably should do - is to have our own arm native runners, get rid of dockerx, get much faster native builds, build in parallel for arm64 and amd64.

Here is also my list of issues, which the users will benefit from (in my opinion, but feel free to change the milestone):
https://github.com/jupyter/docker-stacks/milestone/1
You could take a look here, if you want to do something :)

**Comment by romainx** [comment]
@mathbunnyru thank you for the heads-up, unfortunately I've not so much time to work on open source 😞. However, I will try to have a look this week. This will be an opportunity for me to refresh my memory 😄.
