### ISSUE TITLE
Port 1000 worked but not port 8888 as informed and expected in the documentation and console log

### ISSUE THREAD

**Issue by analistacarlosh** [jupyter/docker-stacks#1505]
Following this reference: https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html

My OS: Mac OS Catalina

**Docker image that I'm using**
`jupyter/datascience-notebook:33add21fab64`

**I've run to launch the container**
`docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "${PWD}":/home/jovyan/work jupyter/datascience-notebook:33add21fab64`

** What steps do you take once the container is running to reproduce the issue?**
1. run: docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "${PWD}":/home/jovyan/work jupyter/datascience-notebook:33add21fab64
2. Visited: <http://localhost:8888> 

** What do you expect to happen?**
Get success when accessing:
http://5b2afbd18035:8888/lab?token=044e9bd35dd49a343b687cd313e0ecaf890d458c361e8bd7
        http://127.0.0.1:8888/lab?token=044e9bd35dd49a343b687cd313e0ecaf890d458c361e8bd7

As the console message says:
<img width="766" alt="Captura de Tela 2021-10-30 às 18 31 26" src="https://user-images.githubusercontent.com/2495963/139558843-2ed95118-ea0f-4f50-8579-e7cceefdc22e.png">

**What actually happens?**
Got this error:
<img width="931" alt="Captura de Tela 2021-10-30 às 18 13 17" src="https://user-images.githubusercontent.com/2495963/139558902-2036f5fd-560f-4698-9540-928b825c8878.png">

## Fixed: used the 10000 number port instead of 8888
Worked as expected accessing: http://127.0.0.1:10000/lab/tree/work

<img width="1016" alt="Captura de Tela 2021-10-30 às 18 13 24" src="https://user-images.githubusercontent.com/2495963/139559093-c6034862-5f56-4d6d-86a6-c87592f4588e.png">

## Question to improve/fix it definitely?
* 1 - Which port is expected to work really?
http://127.0.0.1:8888
or http://127.0.0.1:10000

* 2 -Is it just a correct port usage information issue in the console log or an issue in the Docker Image?

**Comment by mathbunnyru** [comment]
I think everything works perfectly fine here.

`-p 10000:8888` means docker port forwarding.
You launch your application with some port.
It happens that jupyter applications use port 8888 by default.
Then, you want to publish this port outside of the docker container to make your jupyter environment available.
That's why you use `-p 10000:8888`.
But the application doesn't know anything about the forwarded port so you get the logs with 8888.

The docs are also correct:
In the example 1 we use port 8888, and examples 2 and 3 mention, that
```
but it exposes the server on host port 10000 instead of port 8888. Visiting http://<hostname>:10000/?token=<token> in a browser loads Jupyter Notebook server
```

Hopes it makes everything clear.
