### ISSUE TITLE
Has anyone got the notebook working on EC2?

### ISSUE THREAD

**Issue by Cally99** [jupyter/docker-stacks#1529]
I've been tinkering around with this repo for a few days. If I leave the web browser open when it's up and running I'll get failed to connect.
I'm on EC2 and connecting like so

11.22.22.22:8888/login?next=%2Ftree%3Ftoken%bighlongtoken

After a few refreshes I eventually see the home page and the work directory.
After about 20 mins of work and if I leave the browser unattended it fails to connect.

Has anyone got this working well on ec2?
I'm not even doing heavy workloads basic fetching data from a rest api online using a python api wrapper.

**Comment by Bidek56** [comment]
Yes, I use it on EC2 all the time and it works just fine. Although I am connecting thru VPC, not using the public IP.
Jupyter notebooks use websockets, please check your browser dev tools for any connections issues.

**Comment by mathbunnyru** [comment]
@Cally99 what you can do:
- run vanilla jupyter notebook on you server, not the docker images. If the issue still persists, unfortunately, the problem is not in our images.
- Try to understand what happens using logs - there might be connection errors, for example.
- Quite an important thing to do - choose EC2 instance somewhere nearby, it might not fully solve, but can significantly improve your experience.

**Comment by mathbunnyru** [comment]
I think the issue is resolved, because there was no message from @Cally99 .
