### ISSUE TITLE
Missing r-notebook tag(r-3.6.3) in DockerHub

### ISSUE THREAD

**Issue by johnwongapi** [jupyter/docker-stacks#1553]
**What docker image you are using?**

`jupyter/r-notebook`

**What do you expect to happen?**

I know there is a merged [PR](https://github.com/jupyter/docker-stacks/pull/1105) about upgrading R from 3.6.3 to 4.0.
But I expect the old tag should still exist in [DockerHub](https://hub.docker.com/r/jupyter/r-notebook/tags).

**What actually happens?**
I cannot find the r-3.6.3 tag in `jupyter/r-notebook` [DockerHub](https://hub.docker.com/r/jupyter/r-notebook/tags)

**Comment by mathbunnyru** [comment]
This PR was merged `6 Jun 2020`.
We only had reliable and correct tagging for least than a year, that's why it's not there.
I suggest you choose the commit before the merge date and use this hash as a tag.
Or simply scroll several dockerhub pages till you get builds before `6 Jun 2020`.

Closing this issue, because now tags work quite well (for amd64 at least).
