### ISSUE TITLE
Does "The Dirty Pipe Vulnerability" (CVE-2022-0847) affect on jupyter/docker-stacks ?

### ISSUE THREAD

**Issue by wapa5pow** [jupyter/docker-stacks#1648]
### What docker image(s) are you using?

all-spark-notebook, base-notebook, datascience-notebook, minimal-notebook, pyspark-notebook, r-notebook, scipy-notebook, tensorflow-notebook

### OS system and architecture running docker image

Ubuntu

### What Docker command are you running?

```
$ docker run -it docker.io/jupyter/tensorflow-notebook:2022-03-09 uname -a
Linux 19aa791cbaaf 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### How to Reproduce the problem?

N/A

### Actual behavior

N/A

### Anything else?

Does the latest version of jupyter/docker-stacks images fix "CVE-2022-0847" problem?

**Comment by rigzba21** [comment]
Here's the [Ubuntu CVE-2022-0847 patch status](https://ubuntu.com/security/CVE-2022-0847) page. 

It looks like the [latest `ubuntu:focal` image tag](https://hub.docker.com/layers/ubuntu/library/ubuntu/focal/images/sha256-9c152418e380c6e6dd7e19567bb6762b67e22b1d0612e4f5074bda6e6040c64a?context=explore) is from nine days ago. 

The [latest `base-notebook`](https://hub.docker.com/layers/jupyter/base-notebook/latest/images/sha256-56566c14e2efe9345814b9f9e3c60523a4b237d6e9f3cad73352ec0efa40355e?context=explore) tag is from four days ago. 

I'm not sure if this has been patched yet in Ubuntu.

**Comment by mathbunnyru** [comment]
Note: I'm not a security engineer at all.

Our current docker files are written in a way that we are as safe as the latest images / applications.
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile

1. We use `ubuntu:focal` without pinning particular build.
2. We also do `apt upgrade` in case some app was vulnerable and has been fixed.
3. We rebuild our images weekly.

Unfortunately, I'm not sure we can do better than this.

I need to mention, that due to current build process complexity, we might sometimes pull the previous jupyter image and not use the one we have just built.
This is an important issue in progress and some amazing work has already been started by @trallard in https://github.com/jupyter/docker-stacks/pull/1631.

Also, it might be possible that this issue depends on the kernel version of the host system, though I'm not sure at all.
If the issue is fixed in the upstream and we need to rebuild our images ASAP, please, ping me, it's easy to do.

**Comment by rigzba21** [comment]
Here's the kernel version running in `jupyter/base-notebook:latest`:
```bash
docker run --rm -it jupyter/base-notebook:latest bash
```
from inside the container:
```bash
uname -r
```
shows `5.10.76-linuxkit`

```bash
cat /proc/version
```
shows:
```bash
Linux version 5.10.76-linuxkit (root@buildkitsandbox) (gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, GNU ld (GNU Binutils) 2.35.2) #1 SMP Mon Nov 8 10:21:19 UTC 2021
```

**Comment by mathbunnyru** [comment]
It's the same version as latest `ubuntu:focal` and it seems to be vulnerable.
https://www.datadoghq.com/blog/dirty-pipe-vulnerability-overview-and-remediation/#check-if-your-system-is-vulnerable

So, we probably need to wait and rebuild images when a new version is available.

**Comment by rigzba21** [comment]
Here's a recent open issue https://github.com/tianon/docker-brew-ubuntu-core/issues/232 to update the `ubuntu:focal` container with the fix.

**Comment by mathbunnyru** [comment]
Thanks @rigzba21 ! I subscribed to the issue and when the issue is closed, I will rebuild our images.

**Comment by mathbunnyru** [comment]
```
docker run --rm -it ubuntu:focal
root@56ac321e01fb:/# uname -r
5.10.104-linuxkit
```

Base images seem to not be vulnerable anymore.
I will rebuild our images to make sure they are fine as well.

**Comment by rigzba21** [comment]
@mathbunnyru do you think it may be worthwhile to use the sha256 image digest for `ubuntu:focal` in the `Dockerfile`, that way we know exactly which image is used as the root container?   
example:
```Dockerfile
ARG ROOT_CONTAINER=ubuntu:focal@sha256:<SHA_256_DIGEST>
```

**Comment by mathbunnyru** [comment]
No, I don't think that's necessary:
- We only push from GitHub environment, which doesn't contain any pulled images (I hope so), so we will end up with pulling latest version
- We can't pin sha256, because we have to support both amd64/aarch64.

**Comment by rigzba21** [comment]
Ah, gotcha. I forgot about aarch64. Thank you for clarifying!

**Comment by benz0li** [comment]
> I will rebuild our images to make sure they are fine as well.

IMHO CVE-2022-0847 ("The Dirty Pipe Vulnerability") can't be fixed in the image because containers share the host machine’s Linux kernel.

`uname -r` prints the host's system information, returning `*-linuxkit` if the container is run with Docker Desktop.

**Comment by mathbunnyru** [comment]
Thank you @benz0li.

Anyways, our images have been rebuilt a couple of times already, so we should be fine no matter what and there is nothing we can do.
Note: some images, like tensorflow might need a bit more rebuilds, because we sometimes end up pulling images instead of using fresh builds, but that's another problem and I hope we will resolve it sooner or later.
