### ISSUE TITLE
How to become "Project Jupyter" member?

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1664]
I would like to ask what it takes to become a project jupyter member.
And what responsibilities it implies :)

I've been super-concentrated on one repository (I believe it is one of the core repositories) and I might take a look at something else :smile:
It doesn't mean, that I'll stop maintaining this repository, but I don't have a lot of ideas to implement here (apart from the new build system).

**Comment by mathbunnyru** [comment]
@consideRatio you might know the answer here :)

**Comment by consideRatio** [comment]
:heart: :tada: I'm very happy seeing how you have helped this project so much and would love to see help the broader Jupyter ecosystem as well!

I'll need to explore this question a bit myself because its not really clear to me either!

### GitHub organizations and associated teams

There are several parts of Jupyter with different GitHub organizations: Jupyter, Jupyter-Server, JupyterHub, JupyterLab, and maybe more that I missed. I think the Jupyter ecosystem of people have grouped in teams with some people overlapping between organizations/teams. I'm an admin of the JupyterHub organization currently and don't do much in other organizations besides reporting bugs etc.

In JupyterHub we have this process on nominating someone to become a JupyterHub team member as declared here, it is: https://jupyterhub-team-compass.readthedocs.io/en/latest/team/adding-members.html. I think how other teams operate may be similar but I think perhaps JupyterHub has taken the lead on formalizing this a bit more than others have.

I think not so many projects live in the github.com/jupyter organization actually. A lot of the work is put into the notebook project, but that transitions to the jupyter-server/jupyter_server org/project now. The jupyter/docker-stacks project is quite a standalone project which makes it not couple so tightly with other teams development effort.

### Recognition for contributions

In the past, recognition was often provided by granting long term active maintainers a vote in a steering council I think. That was perceived as unsustainable though and another form of recognition developed, the Jupyter distinguished contributors. There are ten people nominated yearly (see https://jupyter.org/about, https://jupyter.org/governance/distinguished_contributors.html, https://discourse.jupyter.org/t/new-jupyter-distinguished-contributors/13459).

### Responsibilities/Expectations

> [...] they should already be a consistent, positive, productive member of the community. 

I think may be the most concrete answer I've found on expectations, taken from the JupyterHub team member documentation linked previously.

### Personal experience and a suggestion

I entered the world of open source by learning about, using, and contributing back to jupyterhub/zero-to-jupyterhub-k8s. To me, that was great because it was a project in active development with several team members working on it. I keep learning from them with regards to Python, Kubernetes, git, how to communicate, maintenance processes, and all kinds of aspects they have acquired experience in.

That project connected many pieces. It was a distribution of JupyterHub - a way to install it in Kubernetes. Since it was that, I ended up needing to learn about all related JupyterHub projects: jupyterhub itself, oauthenticator, configurable-http-proxy, kubespawner, and other projects because they coupled with each other!

I guess generally that engaging in those projects that are coupling to others are a bit special as it helps you learn a lot from the relevant tech in all projects, connect with a lot of people via the involved projects, etc. If the project is something you actively use or work with, it is far more motivating as well. Each project can couple with different type of tech as well.

I suggest that if you want to deepen your involvement in the Jupyter ecosystem in general, I suggest involving yourself in a project connected to many other projects and people.

---

Thanks for raising this question explicitly @mathbunnyru! I'm sorry there wasn't a more clear answer than this - the process for these things also needs contributions!

**Comment by choldgraf** [comment]
Two quick thoughts:

- First, **thank you @mathbunnyru** for all of the work you've put into this repository. The Docker Stacks repository is a huge part of Jupyter's efforts, even though it doesn't cleanly fit underneath one of the major organizations like jupyterhub/jupyterlab/etc. I appreciate your work and already consider you a part of the Jupyter team myself :-)
- Second, what kind of work are you interested in doing with the broader community? It might be helpful to begin with your interests, skills, or skills you'd _like_ to learn. That could help point you in a direction.

That said, just to re-iterate, you shouldn't feel like you *must* contribute to some other package in order to feel like you're a part of the community - the work you're putting in here is already significant and appreciated.

**Comment by afshin** [comment]
As we ramp up the new governance structure of Project Jupyter, the answer to this question becomes clearer. The Docker Stacks effort falls in the **Jupyter Foundations** Subproject (here is [a list of official Jupyter Subprojects](https://jupyter.org/governance/list_of_subprojects.html)).

The Subprojects are in the process of [bootstrapping](https://jupyter.org/governance/bootstrapping_decision_making.html) their individual councils for decision-making. So one natural first official membership in Project Jupyter for many people is to be added to the voting body of the Subproject they work on. Jupyter Foundations is still in the early phase of this transition but I think that's one avenue that is relevant to your question, @mathbunnyru.

**Comment by mathbunnyru** [comment]
Thank you all for your answers! ❤️ 

I will think about what skills I would like to learn further for a while and then I think I will be able to better understand where I can put my efforts, so both jupyter projects and me are happy :)

**Comment by trallard** [comment]
Thanks for asking this question @mathbunnyru - I _many of us_ have had a flavour of this question at some point in our head so having these here in the open is useful

**Comment by mathbunnyru** [comment]
I finally merged a PR with huge changes to our build system.
If there is an application for `Jupyter distinguished contributors`, I would definitely like to apply 😂

**Comment by mathbunnyru** [comment]
I've been added as a project jupyter github member around a week ago, so I think I can close this :)

**Comment by benz0li** [comment]
@mathbunnyru You are doing a great job!

**Comment by mathbunnyru** [comment]
> @mathbunnyru You are doing a great job!

I really appreciate messages like this.
Thank you so much @benz0li ❤️

**Comment by consideRatio** [comment]
You are amazing @mathbunnyru! Thank you for your thorough work!!!
