### ISSUE TITLE
[BUG] - Docker image `jupyter/minimal-notebook:python-3.9.13` install python version 3.10

### ISSUE THREAD

**Issue by piotr-vimn** [jupyter/docker-stacks#1718]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

linux/amd64

### What Docker command are you running?

n/a

### How to Reproduce the problem?

1. Open https://hub.docker.com/layers/minimal-notebook/jupyter/minimal-notebook/python-3.9.13/images/sha256-702125eb8fb0a6e20d55fc7314fba6421708060e37a7d67dee8bee0a5c1951ca?context=explore
2. Check line 18 of image layer
```
ARG PYTHON_VERSION=3.10
```

### Actual behavior

On docker default is python 3.10 instead of 3.8

**Comment by mathbunnyru** [comment]
Unfortunately, this is a well-known issue.
Instead of building images on top of freshly built ones, we end up using images from dockerhub.
This makes many things really awkward or in many cases wrong.

https://github.com/jupyter/docker-stacks/issues/1407

We will definitely address this issue (see https://github.com/jupyter/docker-stacks/pull/1703), but this is not finished yet, because we don't have self-hosted arm runners (and we actually need them).

For now, I will close this issue, no not have duplicates.
