### ISSUE TITLE
Rename default branch from `master` to `main`

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1740]
I think this is what most repos in `jupyter` do.
We don't have my PRs or a lot of active work here right now, so I don't think it should cause many troubles to developers.

After rename I will also simplify `if master or main or schedule` conditions.

**Comment by consideRatio** [comment]
Lets do this! When you do the rename, note that _it should be done using the GitHub UI to avoid a lot of issues_ rather than by `git push` etc.

To do this, use the "Rename branch" button looking like a pencil:
![image](https://user-images.githubusercontent.com/3837114/177754115-d1a99138-c386-4014-b05b-12a6fccdbe5c.png)

**Comment by mathbunnyru** [comment]
Sure, this is exactly how I wanted to do it :)

**Comment by mathbunnyru** [comment]
Local update:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by mathbunnyru** [comment]
@consideRatio I would like to change the default branch name here: https://github.com/jupyter/cookiecutter-docker-stacks
But I don't have admin permissions.
Could you give them to me, please?
