### ISSUE TITLE
Update R to 4.2.1 version

### ISSUE THREAD

**Issue by bo44arov** [jupyter/docker-stacks#1747]
### What docker image(s) is this feature applicable to?

r-notebook

### What changes are you proposing?

- currently R version is 4.1.3. Update it please to the latest 4.2.1

### How does this affect the user?

- user will use the latest version of R language

**Comment by mathbunnyru** [comment]
Hello @bo44arov!

As you can see, we are not pinning any r version in Dockerfile.
https://github.com/jupyter/docker-stacks/blob/main/r-notebook/Dockerfile

Unfortunately, the latest version published to `conda-forge` is 4.1.3 at the moment: https://anaconda.org/conda-forge/r-base/files
There are several PRs with automatic updates of the version, but there seem to be some problem.
https://github.com/conda-forge/r-base-feedstock/pull/212
I think one of the best things you could do is to help resolve issues in the upstream feedstock.

After version 4.2.1 is released, and all packages support it, it will automatically be updated in our images.

**Comment by mathbunnyru** [comment]
I see that r-base 4.2.1 was published to conda-forge.
https://anaconda.org/conda-forge/r-base/files

But still, 4.1.3 is installed by default.
I think it's because we install many r packages and we will have to wait until all of them start supporting new version.
I hope it's not gonna take a lot of time.

**Comment by bo44arov** [comment]
ok, thanks for update
