### ISSUE TITLE
[ENH] - Add `r-arrow` to both `datascience-notebook` and `r-notebook`

### ISSUE THREAD

**Issue by wsphd** [jupyter/docker-stacks#1759]
### What docker image(s) is this feature applicable to?

datascience-notebook, r-notebook

### What changes are you proposing?

Add the [arrow](https://cran.r-project.org/web/packages/arrow/index.html) package to both ../datascience-notebook and ../r-notebook

### How does this affect the user?

Arrow is already in ../pyspark-notebook in this repo and Arrow is increasingly needed to obtain .parquet file interoperability.

**Comment by mathbunnyru** [comment]
I think `py-arrow` in present in `pyspark-notebook`, because `pyspark-notebook` is created specifically for spark users.
At the same time `r-notebook` is about more general `r` related packages.

I would suggest using a child docker image based on the provided ones and to add all the extra packages you need.
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-mamba-install-or-pip-install-in-a-child-docker-image

**Comment by mathbunnyru** [comment]
Closing this issue as we probably won't be adding this package to the mentioned images and there is a better way.
