### ISSUE TITLE
JupyterCon talk

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1832]
Hi everyone,

I'm thinking about giving a talk for JupyterCon about this project.

I would like to cover 2 main topics:

1. What is our project and the ways you can use it (run it as a quick try-and-forget container / a single user on a single machine / jupyterhub / k8s). It should be useful for people, who would like to use our images.
2. How we do what we do (the internals), and what has changed in the past two years. This part will be mostly for the developers, who would like to contribute. I will talk about our build system, GitHub actions/workflows, Docker multi-arch images and start scripts.

Please, let me know your thoughts on this and if you have other ideas for a talk, I would be really happy to hear from you.

**Comment by minrk** [comment]
I think that would be great! I think it's also useful to include a bit about the scope of the project, i.e. when should folks _not_ use it?

**Comment by mathbunnyru** [comment]
@trallard @consideRatio @parente @romainx @maresb if you have any ideas, please share them with me :)

**Comment by maresb** [comment]
I have nowadays largely transitioned to VS Code (the dark side 😔), but I used to use it quite extensively for an exploratory data analysis and development environment so that I could:

* extend it by installing dependencies which my colleagues and I frequently use
* easily sharing this environment while guaranteeing that they can't break it (just restart the container if something goes wrong)
* works just as well locally as in the cloud: a client has sensitive customer data, so we work in their cloud with JupyterLab (and now devcontainers) to avoid the need of downloading or storing any data on our end.

Also, much of what I know know about docker I learned from extensive study and modification of these images.

As to what _not_ to use this image for, I would recommend against trying to use it to extend it further into a large monolithic environment with everything imaginable installed. Lesson learned: that leads quickly to extreme fragility with dependencies. (Although Mamba makes this much easier these days.) In short, make sure custom extensions have limited scope to avoid high maintenance.

**Comment by mathbunnyru** [comment]
Thanks @maresb ❤️

**Comment by bjornjorgensen** [comment]
@maresb you can use VS Code to connect to jupyternote book running on this docker stack. 
Something like [this](https://blog.ouseful.info/2019/02/11/connecting-to-a-remote-jupyter-notebook-server-running-on-digital-ocean-from-microsoft-vs-code/)

**Comment by maresb** [comment]
Thanks! Yes, the two approaches (VS Code and JupyterLab) are certainly not exclusive, with lots of hybrid possibilities. For my particular purposes I've just found it simpler to use micromamba-docker as my base image and start with a fresh environment. But for most people this docker stack image may be simpler since everything is set up, documented and tested.

**Comment by mathbunnyru** [comment]
Here is my proposal. Please, let me know, if you don't like something or would like to add/remove a few things.
https://cfp.jupytercon.com/2023/talk/review/EH7A837AFBWCFJNHENG3QVXMMAKEQKZE

**Comment by mathbunnyru** [comment]
Well, unfortunately, my proposal has not been accepted 😢

**Comment by maresb** [comment]
I'm so sorry!!! I can't imagine why not. :disappointed:

You've done so much awesome work here, and I can only imagine that it must have been due to some sort of logistical constraints. I genuinely hope you're not feeling too discouraged.

**Comment by benz0li** [comment]
@mathbunnyru Keep your spirits up. You are doing great work!

Very much appreciated.

**Comment by mathbunnyru** [comment]
Thank you, @benz0li ❤️ 
Words like these mean so much to me.

**Comment by consideRatio** [comment]
Aaargh sorry to hear that!! You are amazing!!

Btw I hope you can come to JupyterCon anyhow so we can meet IRL.

**Comment by trallard** [comment]
Sorry to hear this! Echoing the sentiment above, you have done an amazing job here and we are lucky to have you on board of this project.

Conferences usually get many more submissions than talks they can accommodate so often great talks are not included in the final programme. 
If you're interested in submitting to other confs I think you'd have a great chance for DockerCon  😉

**Comment by mathbunnyru** [comment]
> Aaargh sorry to hear that!! You are amazing!!
> 
> Btw I hope you can come to JupyterCon anyhow so we can meet IRL.

Thank you, @consideRatio!
It would be really great to meet IRL 🔥 

As I'm currently not employed, I will apply for a financial aid grants, hope I will be able to get it :)
if so, I will definitely come to Paris and we'll have a beer 👍

**Comment by mathbunnyru** [comment]
@trallard, thank you ❤️❤️❤️

> If you're interested in submitting to other confs I think you'd have a great chance for DockerCon 😉

That's a great idea, thank you! I will apple when CFP opens.
I haven't seen the announcement yet, but I think it should happen soon.

**Comment by mathbunnyru** [comment]
Just received a message, that the scholarship process is finalized and I won't receive one (I applied for a Financial Aid).
Sorry, everyone, I probably won't be coming to JupyterCon - even the conference ticket price is quite significant.
Hope to see you some next year 🙂
