### ISSUE TITLE
Support installing RStudio Server on jupyter/datascience-notebook

### ISSUE THREAD

**Issue by ShichenXie** [jupyter/docker-stacks#1908]
### What docker image(s) is this feature applicable to?

datascience-notebook

### What changes are you proposing?

I'm trying to install Rstudio-Server on `jupyter/datascience-notebook:hub-4.0.0`. However, facing error `libc6-i386 : Depends: libc6 (= 2.31-0ubuntu9.9) but 2.35-0ubuntu3.1 is to be installed`. Thanks. 

```
FROM jupyter/datascience-notebook:hub-4.0.0

USER root
WORKDIR /tmp

# https://posit.co/download/rstudio-server/
RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
        file \
        git \
        libapparmor1 \
        libclang-dev \
        libcurl4-openssl-dev \
        libedit2 \
        libobjc4 \
        libssl-dev \
        libpq5 \
        lsb-release \
        psmisc \
        procps \
        python-setuptools \
        pwgen \
        sudo \
        wget 

RUN wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.03.1-446-amd64.deb  -O rstudio-server.deb && \
    dpkg -i rstudio-server.deb && \ 
    rm rstudio-server.deb
```

### How does this affect the user?

New feature for Rstudio users.

**Comment by mathbunnyru** [comment]
@ShichenXie have you been able to install RStudio on top of ubuntu 22.04 ubuntu image?
If not, please, try to do it first, to make sure the problem is not in RStudio itself.

I'm also not sure if RStudio will work properly with conda environment.

And last thing I noticed - the instruction mention using gdebi to install rstudio. It might be worth to check if it works.

**Comment by ShichenXie** [comment]
Thanks. It indeed works. I mistakenly replaced the apt sources with ubuntu 20's in my local environment.
