### ISSUE TITLE
[BUG] - DOCKER_STACKS_JUPYTER_CMD Not Being Recognized when using JupyterHub

### ISSUE THREAD

**Issue by JPGlaser** [jupyter/docker-stacks#1941]
### What docker image(s) are you using?

scipy-notebook

### Host OS system and architecture running docker image

RHEL 7 and 2 x AMD EPYC 7402

### What Docker command are you running?

Standard commands within jupyterhub to spawn Docker Containers.

### How to Reproduce the problem?

1. Build a Docker Container with desired environment.
2. Load in environment variables in main OS via env source file (including setting `DOCKER_STACKS_JUPYTER_CMD` to `nbclassic`.
3. Launch `jupyterhub` with desired settings in `jupyterhub_config.py`.
4. Log into Web Portal.

### Expected behavior

You would see the classic notebook interface.

### Actual behavior

You get the Jupyter Lab interface.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by jmccarrell-asml** [comment]
FWIW, [Switching back to the classic notebook](https://jupyterhub.readthedocs.io/en/stable/howto/configuration/config-user-env.html#switching-back-to-the-classic-notebook) says to set `JUPYTERHUB_SINGLEUSER_APP` to use the classic interface.

**Comment by mathbunnyru** [comment]
@JPGlaser could you please try setting `JUPYTERHUB_SINGLEUSER_APP` for your single-user image?

**Comment by mathbunnyru** [comment]
I think setting `JUPYTERHUB_SINGLEUSER_APP=notebook` should work when using images with `Jupyter Notebook < 7`.
The main code can be found [here](https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/singleuser/app.py).
Also, note, that you can only launch `notebook`, `nbclassic` won't work as well.

Also, this option doesn't work yet with Jupyter Notebook 7, and I created an issue for this: https://github.com/jupyterhub/jupyterhub/issues/4518

When this issue is solved, I will add an if-case to our `start-singleuser.sh` script.
