### ISSUE TITLE
ambiguity around format of .pem file for SSL

### ISSUE THREAD

**Issue by krautt** [jupyter/docker-stacks#198]
Hello, I've tried numerous permutations of pem files in setting up SSL but none seem to work. I've tried key/cert ,  key/cert/intermediate/root.  Can there be documentation on what docker expects?  thanks.

**Comment by parente** [comment]
I dropped the ball on this one. Someone else opened the same issue about fixing the paths to PEM files in the doc AND about documenting what goes in the PEM. The paths got fixed in a PR but the format never got doc'ed. I'll add more detail to the doc soon.

It should be base64 encoded RSA private key + cert(s) to appease Notebook which passes them directly to tornado. That's what the containers generate as a self-signed cert if you specify USE_HTTPS without mounting your own certificate or if you use the Let's Encrypt option in the examples folder.
