### ISSUE TITLE
Create image(s) that only use `main` and not `conda-forge`

### ISSUE THREAD

**Issue by jtroe** [jupyter/docker-stacks#2149]
### What docker image(s) is this feature applicable to?

base-notebook, minimal-notebook, docker-stacks-foundation

### What change(s) are you proposing?

I build an image that I'd like to use `minimal-notebook` (py3.11 currently) as my base image.  For the dependencies I'll be adding, we stick to maintaining compatibility with packages on `main` only currently.  This presents an issue where `conda-forge` is preferred when using this image.  Conda gets upset with me if I try to strictly exclude `conda-forge` since there are a bunch of included dependencies from the channel already installed in the environment.

### How does this affect the user?

Cannot reliably install my downstream package into this image due to `conda-forge` preferences.

**Comment by manics** [comment]
The `main` channel has licensing restrictions so it can't be used by everyone, there's some discussion on Discourse:
https://discourse.jupyter.org/t/conda-forge-only-containers/27548

conda-forge doesn't have any licensing restrictions (other than those that apply to the software packages).

**Comment by mathbunnyru** [comment]
I don't think this is something we will be doing as part of our images - this will require a whole new set of images (we only build one now), create licensing restrictions (mentioned above) and most likely won't gain popularity.

The good news is that you can do it in your fork and it's not that difficult to do so:

1. You have to change the `.condarc` file we're using so it only uses `main` channel: https://github.com/jupyter/docker-stacks/blob/main/images/docker-stacks-foundation/initial-condarc
   This way you won't have a mix of `conda-forge` and `main` packages in the same environment.
2. And then instead of `mamba` you should install and use `conda`.

This is all the diff I got to make the `docker-stacks-foundation` image build fine.

```diff
diff --git a/images/docker-stacks-foundation/Dockerfile b/images/docker-stacks-foundation/Dockerfile
index 3ed18442..7c5a3928 100644
--- a/images/docker-stacks-foundation/Dockerfile
+++ b/images/docker-stacks-foundation/Dockerfile
@@ -126,13 +126,13 @@ RUN set -x && \
         'jupyter_core' \
         # excluding mamba 2.X due to several breaking changes
         # https://github.com/jupyter/docker-stacks/pull/2147
-        'mamba<2.0.0' \
+        'conda' \
         "${PYTHON_SPECIFIER}" && \
     rm -rf /tmp/bin/ && \
     # Pin major.minor version of python
     # https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning
-    mamba list --full-name 'python' | awk 'END{sub("[^.]*$", "*", $2); print $1 " " $2}' >> "${CONDA_DIR}/conda-meta/pinned" && \
-    mamba clean --all -f -y && \
+    conda list --full-name 'python' | awk 'END{sub("[^.]*$", "*", $2); print $1 " " $2}' >> "${CONDA_DIR}/conda-meta/pinned" && \
+    conda clean --all -f -y && \
     fix-permissions "${CONDA_DIR}" && \
     fix-permissions "/home/${NB_USER}"

diff --git a/images/docker-stacks-foundation/initial-condarc b/images/docker-stacks-foundation/initial-condarc
index 383aad3c..c9c5d2d3 100644
--- a/images/docker-stacks-foundation/initial-condarc
+++ b/images/docker-stacks-foundation/initial-condarc
@@ -3,4 +3,4 @@
 auto_update_conda: false
 show_channel_urls: true
 channels:
-  - conda-forge
+  - main
```

This diff is quite small, so it should be easy to merge/rebase our future updates to your fork.

**Comment by mathbunnyru** [comment]
To build a `base-notebook` you only need to replace `mamba install/clean` with `conda install/clean`.
`minimal-notebook` doesn't require any changes at all.

Make sure to build in the right order and that you're not using images provided by us during your builds accidentally (you have to use the ones you build yourself).

I checked the resulting `minimal-notebook` image - it works fine and all the packages are from `main` channel.

**Comment by mathbunnyru** [comment]
As a side note, if lots of users want to have this, please let me know - we can make the diff even smaller.

To do that, we can create a [custom argument](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/custom-images.html#custom-arguments) called `CONDA_EXECUTABLE` (or something like that), and use it everywhere and put `mamba` as default value.

Then the diff will only contain:
1. Setting this variable to `conda`
2. Channel change in `initial-condarc`
3. Installation of `conda` instead of `mamba` (but we'll be able to get rid of it after switching to mamba v2).

It will also allow users to use `conda` instead of `mamba` even without forking our repo (by using `docker bake` with custom arguments)

I don't want to have such a change unless lots of users need it, so, let me know, if you want such a change.

**Comment by jtroe** [comment]
Thanks for the info. I ended up using the guide for using a custom environment and just creating a separate environment. (Larger image size but it worked for my current use case for now) See https://github.com/Esri/arcgis-python-api/blob/6a53a91c7f2c81aab0b04b14f1647d1afe6fbf9d/docker/NotebookImage.Dockerfile if you’re curious.

I will look into creating a forked set of images based on defaults for a future use. That was helpful info. I have found this offering incredibly helpful, so thank you for all your work here.
