### ISSUE TITLE
Use standard path for system condarc instead of /opt/conda/.condarc

### ISSUE THREAD

**Issue by ctcjab** [jupyter/docker-stacks#2173]
### What docker image(s) are you using?

minimal-notebook

### How to Reproduce the problem?

1. Update /opt/conda/.condarc with some config that makes it obvious whether this config is being picked up.

    In my case this is something like `channel_alias: https://artifactory.mycompany.com/artifactory/api/conda/`.

2. Install conda-lock in its own environment (not the base environment), e.g. `conda create -y -n conda-lock -c conda-forge conda-lock`. (You can also use pipx, uvx, pixi global, or your favorite other method of installing a dev tool.
3. Create an `environment.yml` with some config that depends on the config in the system condarc.

    In my case this is something like `channels: [mycompany-internal-channel]` and `dependencies: [mycompany-internal-package]`.
4. Run `conda-lock -f environment.yml` and observe that it fails because it does not pick up the required config from /opt/conda/.condarc.

### Command output

In my case the failure output includes something like
```bash session
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/my-company-internal-channel/noarch/repodata.json] 2756 bytes
```
indicating that it has not correctly picked up the channel_alias configured in `/opt/conda/.condarc`. (If it had, it would have resolved a URL like https://artifactory.mycompany.com/artificatory/api/conda/my-company-internal-channel/noarch/repodata.json which would not have resulted in a 404 error.)

### Expected behavior

I expect the docker-stacks images to use one of the [standardized paths for the system condarc](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc), so that it gets picked up by necessary tools like conda-lock.

### Actual behavior

docker-stacks is using a non-standard path for the system condarc (namely, /opt/conda/.condarc), which means it does not get picked up by conda-lock.

### Latest Docker version

- [x] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
Thank you for the issue.

> docker-stacks is using a non-standard path for the system condarc (namely, /opt/conda/.condarc), which means it does not get picked up by conda-lock.

I think this is an incorrect statement, to be honest.
We're not trying to be system `condarc` at all.

Instead, the correct version would be something like this: docker-stacks is using a **standard path** for the **non-system** condarc (namely, /opt/conda/.condarc), which means it does not get picked up by conda-lock.

And the link you provide (https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc) mentions exactly our use-case: (`"$CONDA_ROOT/.condarc"`).

So, I don't consider this to be a bug.

But the question still stands: **Should our `.condarc` config be a system-wide config or a local config (as it is now)?**

I think it might depend on your use case quite a lot because some people might want to have something else as their system config.
Unfortunately, I don't have enough confidence/experience to make that decision on my own.

@consideRatio @yuvipanda @manics what do you think?

**Comment by minrk** [comment]
I think we're doing the right thing, putting condarc in the standard path for a conda install. It doesn't seem right to me that conda-lock would ignore the condarc of the root conda install, but I guess that's their choice. If you are using conda-lock with its own _conda_ (e.g. via pixi), then I think it's actually correct to ignore our condarc because it's a fully separate conda stack on purpose.

**Comment by manics** [comment]
I also think it's fine at it is.
@ctcjab if you need a custom condarc what's stopping you from putting it in a system location?

**Comment by ctcjab** [comment]
> If you are using conda-lock with its own conda (e.g. via pixi), then I think it's actually correct to ignore our condarc because it's a fully separate conda stack on purpose.

conda-lock always uses its own bundled / [vendored version of conda](https://github.com/conda/conda-lock/tree/main/conda_lock/_vendor/conda), whether you install it via conda, pixi, pip, or whatever else. Since conda calculates the `sys_rc_path` [based on sys.prefix](https://github.com/conda/conda-lock/blob/v2.5.7/conda_lock/_vendor/conda/base/context.py#L99), the only way you can install conda-lock in these images such that it picks up /opt/conda/.condarc is if you install it in the conda "base" env so that the sys.prefix of the bundled conda coincides with the sys.prefix of the base env's conda installation.

> But the question still stands: Should our .condarc config be a system-wide config or a local config (as it is now)?

I agree that this is the key question here. My assumption was that the conda installation you provide in these images expects to be a system-wide, global conda installation, and therefore its system config should go in `/etc/conda/condarc`, because it is installed in a system global path (namely `/opt/conda`) rather than a user-specific path like `~/conda` or `/external/mount/USERNAME/conda`. Also, these are "single-user" containers after all -- there are never multiple users in the same container who need their own separate installations of conda alongside one another on the same filesystem.

I guess you could try to find out how many of your users actually do need to install their own separate conda installations (either somewhere user-specific like `~/conda` or system global like `/usr/local/conda`). In this case, they may not want those separate installations to pick up the global config you're currently putting in `/opt/conda`. But that seems like a much rarer case; I'd guess most or all of your users only need the single conda installation that you provide in /opt (indeed, one reason they're using these images is they only need a single conda installation and not anything more complicated, so these images fit the bill), in which case these users expect the global config you provide to be picked up by tools like conda-lock no matter where conda-lock is installed.

One other consideration, in case anyone proposes copying the `/opt/conda/.condarc` into `/home/jovyan` to ensure that it gets picked up by conda-lock: These images are often used in contexts like [Zero to JupyterHub](https://z2jh.jupyter.org/), where the /home/jovyan in the image is shadowed by a Kubernetes Persistent Volume. That makes using the home directory an unmaintainable option for what should be global config that the user should be able to pick up changes to as new versions of the image are pushed out.

**Comment by ctcjab** [comment]
> @ctcjab if you need a custom condarc what's stopping you from putting it in a system location?

Indeed, now that I know I need to, I am removing your /opt/conda/.condarc and replacing it with /etc/conda/condarc. But before I got that far, it took me quite a while to debug why conda-lock was behaving differently depending on how it was installed, and I figured I would open this issue to propose a change that would have saved me (and I presume other users in the future) some time and grief.

**Comment by minrk** [comment]
We set options for the conda installation that we manage, not the system. So if other conda installations are made, it seems appropriate to me that they would not share our conda configuration.

I think the issue boils down to the fact that conda-lock, apparently as an implementation detail, uses its own conda installation. But this implementation detail has (intentional?) user-facing consequences that don't appear to meet reasonable user expectations of which config will take effect. Maybe conda-lock should change, maybe it should just be documented, but this seems like a conda-lock issue to me.

The general issue of our conda config not affecting other condas still seems to be the correct behavior, and if users want to configure more than one conda with their own config, system-wide config is the place to do that. But we don't currently apply any config that should have that effect, I don't think, so we don't have a reason to put config in that file.

**Comment by mathbunnyru** [comment]
I also agree that the current behaviour of docker-stacks is intuitive to me, but `conda-lock`'s isn't.
So, I agree this is something that should be documented in `conda-lock`'s documentation (or the behaviour should change).
