### ISSUE TITLE
Unable to read S3 file following recipe.

### ISSUE THREAD

**Issue by taeric** [jupyter/docker-stacks#272]
I'm following the [recipe](https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes#using-pyspark-with-aws-s3) on loading S3 files in a notebook.  Right now, this is dropping out with an error regarding:

```
Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3native.NativeS3FileSystem not found
```

The code snippet I'm running to make this happen is:

```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.10.34,org.apache.hadoop:hadoop-aws:2.6.0 pyspark-shell'

hadoopConf = sc._jsc.hadoopConfiguration()
hadoopConf.set("fs.s3.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
hadoopConf.set("fs.s3.awsAccessKeyId", myAccessKey)
hadoopConf.set("fs.s3.awsSecretAccessKey", mySecretKey)

csv = sc.textFile("s3://path/to/my/file.csv")

csv.takeSample(False, 20, 1)
```

Apologies if I am missing some other steps.  In particular, I have not copied any new files to my container.  The container I am running was launched with:

```
docker run -d -p 8888:8888 jupyter/all-spark-notebook
```

Any help to get this working is greatly appreciated.  Thanks!

**Comment by parente** [comment]
Maybe @ksindi, who wrote the original recipe, can help.

**Comment by taeric** [comment]
I found my problem.  Since I had to rearrange a few things to keep from having to restart the entire kernel every time I wanted to run things, I did not pay attention to the fact that I moved the section of

```
import pyspark
sc = pyspark.SparkContext("local[*]")
```

Above the section that had:

```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.10.34,org.apache.hadoop:hadoop-aws:2.6.0,com.databricks:spark-csv_2.11:1.4.0 pyspark-shell'
```

Making sure these were in the correct order seems to have fixed my problem.

**Comment by taeric** [comment]
I spoke a little too soon.  I found *a* problem, but did not completely solve it.

Looking at the docs for the credentials I am trying to use, I believe I have to use the "s3a" specifier.  Unfortunately, this leads me to the following exceptions:

```
Py4JJavaError: An error occurred while calling o444.load.
: com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: B67B942CF0C4C824, AWS Error Code: null, AWS Error Message: Forbidden, S3 Extended Request ID: xjDaQe8kZnOpCp91VEPraY5N1V95bVwboiUw8tASiqyBFgo4AcZTte3NvHoIS8TyIv0f0/NO+dU=
```

I tried many iterations of different versions of the packages.  In particular, I tried with the latest aws-sdk.  Unfortunately, that leads me to some classpath issues with httpclient.

For now, I am moving on and just playing with some local files.  Still, if anyone knows how I can use aws roles to connect to a private s3 bucket, that would be greatly appreciated.  Thanks!

**Comment by ksindi** [comment]
@taeric this article might help: http://deploymentzone.com/2015/12/20/s3a-on-spark-on-aws-ec2/

**Comment by taeric** [comment]
Sadly, that didn't seem to help.  I'm shelving this for a bit.  I think I'm going to focus on just connecting to a spark cluster that is running in EMR.  In which case, much of the permissions issue with S3 go away.  (Granted, this just shifts the goal posts to connecting to the cluster...)

At any rate, feel free to close this out.  If you want me to try anything, in particular, before this is closed, please let me know.  I'd love to help out in this experience.

**Comment by mjg232** [comment]
@taeric were you able to get this woring?  I'm having a similar (same) problem from scala as reported here:
https://github.com/jupyter/docker-stacks/issues/277

**Comment by taeric** [comment]
My apologies, mjg232@, I did not see this.

Unfortunately, I did not get this working  I plan on trying again soon.  Currently swamped with some other work, but should be able to play around some more within a week.

For me, I was definitely able to use s3n paths.  I just couldn't hit private buckets.

**Comment by parente** [comment]
#263 has the upgrade to Spark 2.0.2 with a compatible build of Toree.

**Comment by parente** [comment]
This issue has been inactive for a few months now and doesn't appear to be a problem with the images here. I'm going to close it out.

If anyone gets an example of reading S3 from Spark, please do open a PR or update the recipes page on the wiki.

**Comment by bharath02** [comment]
i am working for solving error,

 ERROR:py4JJavaError: An error occurred while calling o88.csv. : java.lang.NoClassDefFoundError: org/jets3t/service/S3ServiceException


error rose  reading data from AWS S3 buckect to pyspark.
data=spark.read.csv("s3a://bucketname/filename")
pls help me  how to solve

**Comment by leewallen** [comment]
@bharath02 - You could try building a docker image using the docker-stacks image you were trying to use as the base image, and then add this: 

`RUN (cd /usr/local/spark/jars && curl -O https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar)`

I did that (and included the hadoop-aws jar and aws java SDK jar) and had things working for a little while. 

Unfortunately I made further changes, switched base docker images from `all-spark-notebook` to `pyspark-notebook`, and things stopped working again. I was making changes over the period of a week without making notes of what I had done and without fully testing since I was using it for home use for a fun learning project.

Lessons learned:

- Keep a local git repo, and make branches from main, when making changes
- Reference specific docker images for your base images instead of using latest
- Use a build system (or just be diligent) and make unique labels for your docker image you're building so you can step back and see how something changed if your newer docker image seems to stop working (which would also help you verify that the issue is with your image and not an external change)

I knew better but wasn't doing any of those steps because "I'll get to it later."

I realize you posted this question 8 months ago - if you resolved the issue, then please post what your changes were. Useful info would be what image and label you're using (all-spark-notebook, pyspark-notebook, scipy-notebook, etc), which version of spark/hadoop/AWS java SDK, etc, and how you configured your spark context. 

If you haven't resolved the issue, then please share the above info anyway. It might help someone spot the issue.

Good luck!
