### ISSUE TITLE
spark 2.0 jupyter/all-spark-notebook image anyone?

### ISSUE THREAD

**Issue by mjg232** [jupyter/docker-stacks#288]
I'm continuing to have problems connecting to S3 on remote spark clusters (see issue #277) but spark 2.0 seems to solve the problem on the backend.  Now I need a jupyter toree built against spark 2.0 but that's proving to be more difficult to build than I would have hoped.

does anyone have a spark 2.0 jupyter/all-spark-notebook docker image to share?
thanks in advance!

**Comment by parente** [comment]
I think Toree is waiting ona release of JeroMQ under the Mozilla license. Once that happens, Toree can make a release that we can install here.

/cc @lbustelo @mariusvniekerk

**Comment by parente** [comment]
Ref https://github.com/zeromq/jeromq/issues/360

**Comment by rgbkrk** [comment]
I'm looking forward to that Toree release for Spark 2.0 too.

**Comment by mjg232** [comment]
can't wait @parente !

**Comment by parente** [comment]
Vote for Toree 0.1.0 RC2 has been called: https://www.mail-archive.com/dev@toree.incubator.apache.org/msg00750.html

**Comment by mjg232** [comment]
very exciting @parente -- thanks!

**Comment by lbustelo** [comment]
That release does not support Spark 2.0. Be in the lookout for 0.2.0 right after that. 

Gino B.

**Comment by parente** [comment]
Doh. Right. Getting ahead of myself.

**Comment by maltefiala** [comment]
One of our customers needed this badly, so we did it ourselves, see the related [github repo](https://github.com/maltefiala/docker--jupyter-pyspark) and the [dockerhub repo](https://hub.docker.com/r/produktion/jupyter-pyspark).

We decided to stay as close as possible to the original jupyter images. All steps from jupyter have therefore been reproduced. However, we use spark standalone instead of mesos and use the [official openjdk 8](https://github.com/maltefiala/docker--jupyter-openjdk/blob/master/Dockerfile) recipe.

**Comment by parente** [comment]
Merged #263 with Spark 2.0.2 in it. Appears in docker image tag `2410ad57203a` (currently latest).

**Comment by maltefiala** [comment]
Removed mentioned repo and switched to official docker files.

**Comment by parente** [comment]
We should get 2.1.1 here soon.
