### ISSUE TITLE
Add Jupyterlab stack

### ISSUE THREAD

**Issue by donaldbraman** [jupyter/docker-stacks#299]
Add stack for jupyterlab.  As noted here, https://github.com/jupyterlab/jupyterlab/issues/1036, should be pretty simple: 

```
FROM jupyter/scipy-notebook
RUN pip install jupyterlab && \
    jupyter serverextension enable --py jupyterlab
CMD ["start.sh", "jupyter", "lab"]
```

Happy to submit a PR if that's helpful.

**Comment by parente** [comment]
Hi @donaldbraman. Thanks for the suggestion. There's a section on the recipes wiki page with this information: https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#run-jupyter-lab

We didn't make it a standalone stack because it's not clear where it would fit in the hierarchy. Would it be the equivalent of scipy-notebook, all-spark-notebook, pyspark-notebook? Would we need a whole new tree for lab? It seemed simplest to document how users could extend any of the existing images to run lab instead of classic notebook.

**Comment by donaldbraman** [comment]
Makes sense -- very nice docs.

**Comment by parente** [comment]
Thanks @donaldbraman . If you have any improvements you'd like to make to the wiki, please do!
