### ISSUE TITLE
Pass token throw environment variables

### ISSUE THREAD

**Issue by egorlitvinenko** [jupyter/docker-stacks#343]
Hi, thanks for your work!

I'm trying to solve in the best way the problem mentioned in topic.
Original task - run docker images from Marathon. The external system should know Jupyter token and will be responsible for authorization. 
 I didn't find a way to solve it throw Marathon. I tried to pass token throw Marathon in this way:
```
"docker": {
      "parameters": [
          { "key" : "entrypoint", "value" : "start-notebook.sh --NotebookApp.token='123'" }
      ],
    }
```

It doesn't work because of error:

`starting container process caused \"exec: \\\"start-notebook.sh --NotebookApp.token='123'\\\": executable file not found in $PATH\"\n".`

Generally, I think that it will be better that system generates token and path it throw environment variables into docker container for Jupyter, if it will be supported.
I'm able to make PR for start-singleuser.sh script.

What do you think?

Please, provide feedback as soon as possible, cause it's urgent task.

In best regards

**Comment by parente** [comment]
We've been trying to cut down on the number of environment variables supported by start-notebook.sh that simply mirror what Jupyter already supports as command line args.

A few things to try:

* You probably don't want to override entrypoint. We use tini as the entrypoint in the images because it's a proper init process. Running the notebook server as the entrypoint can lead to bad behaviors (e.g., kernels crash immediately on launch).
* It looks like marathon is treating the entire value as the command to run. Can it support a list in the docker command value field so that you can pass the script name and arg values separately? Or does it support separate command and command arg fields?
* You mentioned generating tokens. I don't know if it fits your use case, but the notebook server will default to automatically generate tokens if you don't pass any `--NotebookApp.token` arg. (I'm guessing you meant the marathon system, however, so that you can get the token back to the user who needs it to login.)

**Comment by egorlitvinenko** [comment]
With Marathon I can successfully do this:
```
"cmd": "start-notebook.sh --NotebookApp.token=$SOME_TOKEN"
"env": { "SOME_TOKEN": "qwerty" }
```
And jupyter is opened and looks like all is good. How can I check the state?

**Comment by parente** [comment]
I don't know a way to get the token back. Is it possible to have Marathon generate a unique token for each container it launches and store that information somewhere for retrieval?

**Comment by parente** [comment]
This issue has been idle for close to two months so I'm going to close it. @egorlitvinenko if you've found a way to get the images with tokens working in Marathon, it would be great to see your solution posted on the https://github.com/jupyter/docker-stacks/wiki/Docker-recipes page.
