### ISSUE TITLE
Who is jovyan?

### ISSUE THREAD

**Issue by dfrankow** [jupyter/docker-stacks#358]
I understand that is the user created in the docker files, but where did that username come from?

Just curious.

**Comment by jakirkham** [comment]
ref: https://github.com/jovyan ?

**Comment by parente** [comment]
[Jovian](https://www.google.com/search?q=jovian) means "related to Jupiter", ergo jovyan and Jupyter.

I didn't come up with it. @rgbkrk or @minrk or someone who worked on the original docker-demo-image did and should chime in if I'm wrong.

**Comment by dfrankow** [comment]
Ah gotcha. Thanks!

**Comment by rgbkrk** [comment]
**Jo·vy·an**
/ˈjōvēən/

_noun_ – an inhabitant of Jupyter

------------------------

I coined it sometime ago to refer to Jupyter users (including myself).

**Comment by rgbkrk** [comment]
When I say "I" coined it I mean that I [ripped it off from science fiction](https://en.wikipedia.org/wiki/Jovian).

**Comment by vtslab** [comment]
Note that the spelling Jovyan instead of Jovian is awkward at first sight because of the original spelling in Latin: https://en.wikipedia.org/wiki/Jupiter_(mythology) 
However, in analogy with the Jupyter spelling, the Jovyan spelling makes sense.

**Comment by TatianaShavrina** [comment]
Really thought for some time this was some Armenian developer's surname lol

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-community-calls/668/66

**Comment by 3-w-c** [comment]
> Note that the spelling Jovyan instead of Jovian is awkward at first sight because of the original spelling in Latin

Me (and [apparently ~237 other people](https://github.com/search?q=joyvan&type=code)) typoed this as `joyvan`, which is a huge foot-gun because Docker will happily create a `/home/joyvan` volume without error, and you'll only notice that data is not as persistent as you think it will be when the container restarts :see_no_evil:

If it's not, as I guess it is, *far* too late to change this, I think `jovian` would be a lot clearer, because it's very visibly different from the typo'd `joivan`.
