### ISSUE TITLE
Upgrade to Python 3.6 and IPython 6.0

### ISSUE THREAD

**Issue by Bidek56** [jupyter/docker-stacks#379]
What is the best way of upgrading to Python 3.6, IPython 6.0 and Conda 4.3 given the many layers of Docker files? Thanks

**Comment by parente** [comment]
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile has the miniconda version which implies the root environment Python version. I think notebook drags in IPython by default, so the next complete rebuild with that change will pull IPython 6.0. Maybe we should make that version explicit in base-notebook as well so that we can rev it by bumping the ipython package version number like all the other packages.

**Comment by krosaen** [comment]
I notice https://github.com/jupyter/docker-stacks/commit/3f9e3b66c64f9239b1196f9db2200bdb694371cb reverts a previous attempt to bump the miniconda version, perhaps @basnijholt can comment as to why? Guessing it caused issues and bumping conda is a bigger undertaking than it seems...

**Comment by jakirkham** [comment]
I would expect that [this]( https://github.com/jupyter/docker-stacks/pull/350#issuecomment-286128364 ) is the answer.

**Comment by parente** [comment]
Unblocked by #404
