### ISSUE TITLE
Use R packages from conda-forge

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#382]
Amazing work: https://github.com/conda-forge/staged-recipes/issues/2009. Let's try to use it!

**Comment by parente** [comment]
I gave this a first shot and found that irkernel failed to launch do to a missing PC symbol in the readline package. Needs investigation.

**Comment by jakirkham** [comment]
Are we sure the `conda-forge` copy of `readline` is present? There have been reports of the `PC` symbol not being present when `defaults` copy of `readline` is used.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/189

**Comment by parente** [comment]
It's highly probable that's the issue. Disclaimer: I spent a grand total of 5 minutes trying the switchover and it's totally on me to do more research.

**Comment by jakirkham** [comment]
It's always possible there is a different issue. Just the missing PC symbol sounded too familiar. Either way it will be good to know.

**Comment by parente** [comment]
It was indeed readline from defaults. Forcing a `conda update --all` after giving conda-forge priority fixed that problem.

irkernel now works as long as libxrender1, libsm6, and libxext-dev are all installed as debian packages, else cairo fails to load with:

```
Error in dev.control(displaylist = "enable") :
  dev.control() called without an open graphics device
Calls: <Anonymous> ... tryCatch -> tryCatchList -> evaluate -> dev.control
In addition: Warning messages:
1: In ok_device(filename, ...) :
  unable to load shared object '/opt/conda/lib/R/library/grDevices/libs//cairo.so':
  libSM.so.6: cannot open shared object file: No such file or directory
2: In ok_device(filename, ...) : failed to load cairo DLL
Execution halted
```

This is not a new requirement. At least the first two packages were required for r-irkernel from defaults, and I suspect the last one is installed implicitly by one of the apt-get installs done in the minimal-notebook stack.

**Comment by jakirkham** [comment]
Yeah, `libxrender1` and `libxext-dev` are required because of [`r-base`]( https://github.com/conda-forge/r-base-feedstock/blob/0129e2a7f5a63c846904af73dce0de09db3580a1/recipe/yum_requirements.txt#L6-L7 ). Though other things may be using them as well. I think we [included]( https://github.com/conda-forge/docker-images/blob/1335e38070663a5a75407b080a16d19ed0d71156/linux-anvil/Dockerfile#L24-L26 ) them in our Docker image too.

We do have some `yum` packages already in the Docker image. For instance `libsm6` is a preincluded. In some ways we tried to mimic the manylinux effort in the beginning. So we preincluded things that manylinux would have allowed (ignoring the CentOS 5 vs CentOS 6 difference).

Not sure that the other X11 requirements will be needed here as we are not running an X11 server. That said, it may be worth taking a look.

One day we may start using X11 packages from conda-forge as well. We just have to figure out how to best integrate them into the stack.

**Comment by parente** [comment]
Thanks for the background. I got IRkernel launching and plotting properly in #407. I think we're ready to cut over!

**Comment by jakirkham** [comment]
Was just noticing today that there are still a few images that add the `r` channel. Any thoughts on dropping the `r` channel from them as well?

**Comment by parente** [comment]
@jakirkham Interesting. Thought we had got them all switched over. I see `--append channels r` in datascience-notebook which we should fix. Did you spot it elsewhere as well?

**Comment by jakirkham** [comment]
That was the one that I saw as well. Did a couple quick searches and didn't see anything else.

Are there particular packages that we were missing over there that motivated us to keep it? Skimming a [recent build of the datascience-notebook]( https://cloud.docker.com/app/jupyter/repository/registry-1.docker.io/jupyter/datascience-notebook/builds/2db6413b-6854-4580-a97b-055df84ec3e3 ) shows only `conda-forge` packages for `r-*` AFAICT. Suppose we can just try dropping it and see what happens.

On a separate note, the switching to `nomkl` packages that happens in that build is a little strange. Has there already been discussion about this somewhere?

**Comment by jakirkham** [comment]
Added PR ( https://github.com/jupyter/docker-stacks/pull/601 ) to drop the `r` channel vestige.
