### ISSUE TITLE
Doesn't import keras

### ISSUE THREAD

**Issue by galenwilkerson** [jupyter/docker-stacks#463]
Hi, I've just encountered an error importing keras, which shouldn't happen normally.  Thanks for any help.

Error when running this cell:

`import keras`

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-c74e2bd4ca71> in <module>()
----> 1 import keras

ModuleNotFoundError: No module named 'keras'`

Dockerfile:

`############################################################
# Dockerfile to build docker image with additional python libraries

############################################################

FROM jupyter/tensorflow-notebook

RUN conda install --quiet --yes -c anaconda mysql-connector-python 

`

Built using:

`docker -D build -f Dockerfile.jupyter_tensorflow .`

Run using:

`docker run -d -p 8888:8888  -v /home/analysis/:/home/jovyan/work 2bfaf6306e39 start-notebook.sh --NotebookApp.password='<passwordcrypt>'`

`$ uname -a`

`Linux docker 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by parente** [comment]
```
docker pull jupyter/tensorflow-notebook
docker run -it --rm -p 8888:8888 jupyter/tensorflow-notebook
```

and `import keras` worked for me. Do you have the latest tensorflow-notebook image? Docker build does not pull the latest image used in the `FROM` line for you by default.

You should also prefer a specific image tag instead of latest to avoid breaking changes when the latest image revs in incompatible ways. See https://cloud.docker.com/app/parente/repository/docker/jupyter/tensorflow-notebook for the tagged versions and https://github.com/jupyter/docker-stacks/wiki/Docker-build-history for how they relate to PRs and commits here.

**Comment by jakirkham** [comment]
Going to close due to no response. Happy to reopen on a follow up.
