### ISSUE TITLE
File upload size limit question

### ISSUE THREAD

**Issue by ChadSleeman** [jupyter/docker-stacks#470]
Sorry, I am a newb please be gentile...

I am using the jupyter/datscience-notebook image running locally on my PC. 

In Jupyter, when I try to upload any file larger then 1MB nothing happens. I click the upload button and nothing.

If I launch the image so I have sudo access I noticed I can upload files over 1MB.

Looking over the config.py file nothing poops out to me that could be set limiting the file size. I THINK it could be a limit from the web server but I cant find information on what web service the image is running. It does not appear to be using Apache or nginx..

I put a few hours of time into Google and decided it would not hurt to post here and see if I could get some advice. The goal is to upload files over 1MB and not be running as an admin.

Thanks for the help!

**Comment by parente** [comment]
Welcome, @ChadSleeman. I do believe the notebook server does have a 1 MB file upload limit through the web UI by default. If I remember correctly, the limit is actually in the JavaScript of the notebook server, and might not be configurable from the server side.

For questions like this, you might get a faster / better response on the Jupyter Google Group (https://groups.google.com/forum/#!forum/jupyter) since it the question is more about the use of Jupyter Notebook than a specific issue with the Docker images containing Jupyter. No harm in reposting your question there now either to double-check my memory.

**Comment by ChadSleeman** [comment]
The issue is solved! The problem was not in the image/container but in the NGINX config for the swarm server.

Thanks for replying to my question.

Chad
