### ISSUE TITLE
Question:  base-notebook vs. minimal-notebook

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#474]
Can someone provide exact details of the difference between the base-notebook Docker image and the minimal-notebook Docker image?  The file sizes in Docker Hub are quite different, but the descriptions state:

"Minimally-functional Jupyter Notebook 5.1.x (e.g., no pandoc for document conversion)"
vs.
"Fully-functional Jupyter Notebook 5.1.x"

Thanks.

**Comment by parente** [comment]
From https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile#L11, the differences are:

* pandoc + latex are installed, so that notebooks can be converted to PDFs
* emacs, vim, and jed are available for text  editing from a terminal
* git is there for version control
* zip/unzip are installed for dealing with zip files
* build-essential, libxrender1, and inkscape are installed so plotting packages in downstream docker images work properly

**Comment by rwmajor2** [comment]
Thanks @parente.  Do you know what of these things are the biggest culprits of file size?  In Docker Hub, the compressed size of the base-notebook is 188MB but the minimal-notebook is 967MB.

**Comment by parente** [comment]
Taking a guess from past experience, pandoc and texlive packages add the majority of the bytes.
