### ISSUE TITLE
Do Jupyter Docker Support Spark Cluster with Yarn?

### ISSUE THREAD

**Issue by mango22** [jupyter/docker-stacks#515]
Hello,

Documentation talks about Spark standalone and Spark cluster on Memos. Wondering if Spark cluster with Yarn is supported or not.

Thanks.

**Comment by parente** [comment]
@mango22 There is a Dockerfile recipe for building a YARN-compatible image on the recipes wiki page: https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#use-jupyterall-spark-notebooks-with-an-existing-sparkyarn-cluster

I'm not sure how up-to-date the recipe is. It was added early in 2017.

**Comment by eromoe** [comment]
we use spark 1.6.2  in yarn mode,  hadoop version is 2.7.2.

1. Should I use same hadoop version as spark in yarn cluster ?
2. I don't see where specific spark version, is it fine 
3. Should -Dhdp.version=2.5.3.0-37 same as the yarn cluster, or it is fine to leave as it be.

I really don't know much about java stacks and spark.

**Comment by parente** [comment]
With the images as they exist today, you have to match the hadoop version we install which is currently  2.7 (https://github.com/jupyter/docker-stacks/blob/master/pyspark-notebook/Dockerfile#L11). The Spark version currently installed is declared here: https://github.com/jupyter/docker-stacks/blob/master/pyspark-notebook/Dockerfile#L10

Issue #626 looks to make the image more version and cluster manager agnostic.

Hope this helps!

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
