### ISSUE TITLE
How to install plotly or vega in the docker image 'jupyter/all-spark-notebook'

### ISSUE THREAD

**Issue by madeinquant** [jupyter/docker-stacks#546]
Encounter erros when import breeze.plot._ in a docker "all-spark-notebook

I try to execute the following source code(https://gist.github.com/satoshihirose/49fac5ad48b39c5970ae) in a docker "all-spark-notebook", however, it cannot be executed in jupyter notebook. An error was encountered. Please comment how to fix it, thank you.

```
Name: Compile Error
Message: <console>:21: error: object plot is not a member of package breeze
           import breeze.plot._
                         ^
<console>:24: error: not found: value Figure
           val f = Figure()
                   ^
StackTrace: 
```

**Comment by parente** [comment]
@madeinquant Can you explain how you added the breeze package to your Docker container and which Scala kernel you're using?

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
