### ISSUE TITLE
Feature request: Apache Drill

### ISSUE THREAD

**Issue by taqtiqa-mark** [jupyter/docker-stacks#599]
Hi! Thanks for using Jupyter's docker-stacks images.

I love the idea of the opinionated/curated stack.

Has [Apache Drill](https://drill.apache.org/) been considered for inclusion?
Is there a road map of upcoming additions?

Thanks again for all your efforts.

**Comment by parente** [comment]
@taqtiqa-mark there's no official roadmap, but we're thinking about how to keep up maintenance on the images here while encouraging the community to create new images. Have a look at #517 and feel free to chime in.

**Comment by taqtiqa-mark** [comment]
Ack maintenance is an issue.

However I'd argue Drill provides a such a generic interface (ANSI-SQL) to so many formats/sources that is should be built into the base notebook. Accept that is a big call.

**Comment by parente** [comment]
Yes. It's hard to draw the line. How about Presto instead of Drill for instance? I can't speak for the other maintainers here, but I'm not all that familiar with either. I think the community would be much better served by someone with a vested interested in Drill (or Presto, or ...) maintaining such an image, starting from the base-notebook or minimal-notebook image defined here for the Jupyter bits.

Just my two cents.

**Comment by cricket007** [comment]
How would Presto or Drill work exactly within the Jupyter kernel? Would it hook to Py4J like Spark does? Use `pyhive` under the scene (not sure if Drill works with that because Drill needs to communicate with Zookeeper)

What if instead of one or the other, it was general JDBC-like kernel (similar to Zeppelin). Or at the very least, some interface into SQLAlchemy, like Apache Superset or [shown here](https://towardsdatascience.com/jupyter-magics-with-sql-921370099589)?

**Comment by parente** [comment]
This issue has been idle for a while now and so I'm going to close it. If someone puts together a recipe for the documentation or community-maintained Docker images containing Drill, Presto, etc., I'll happily review PRs adding links to them in the documentation here.
