### ISSUE TITLE
Build image on Centos 

### ISSUE THREAD

**Issue by SofianeB** [jupyter/docker-stacks#625]
Can I build a base-notebook image based on Centos and not on Ubuntu?
Reason: I have to install other dependencies, which work only on Centos.
Thank you!

**Comment by parente** [comment]
With some time, love, and effort, probably, but I've not tried it. Maybe someone else who has can chime in here.

The way I'd approach it is to fork this repository, change the base-notebook/Dockerfile to start `FROM centos:7`, run `make build/base-notebook`, fix errors (e.g., yum instead of apt-get) as you find them, and iterate until it's built. I don't think anything the base-notebook depends on is only available on Ubuntu.

**Comment by parente** [comment]
Sounds like you're good to go so I'm going to close this out. Feel free to open a new issue if you have other questions.

**Comment by jakirkham** [comment]
FWIW we build a very similar stack to this one at work using CentOS. You would be more than welcome to use any of it that may be helpful.

**Comment by mapsacosta** [comment]
@jakirkham can you please point me to your CentOS stacks? Would be of HUGE help!!
