### ISSUE TITLE
how to define notebook_dir in Dockerspawner 0.9

### ISSUE THREAD

**Issue by wutianchen** [jupyter/docker-stacks#659]
I am using docker-stacks to spawn jupyter notebooks and want to customize the jupyter notebook starting path with the parameters

AppNotebook.notebook_dir
AppNotebook.default_url
AppNotebook.base_url

but I read the documentation https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start-singleuser.sh

```bash
# handle some deprecated environment variables
# from DockerSpawner < 0.8.
# These won't be passed from DockerSpawner 0.9,
# so avoid specifying --arg=empty-string

if [ ! -z "$NOTEBOOK_DIR" ]; then
  NOTEBOOK_ARGS="--notebook-dir='$NOTEBOOK_DIR' $NOTEBOOK_ARGS"
fi
```

how can I control these parameters in DockerSpawner 0.9 ?

**Comment by parente** [comment]
DockerSpawner has an example that shows how to set `notebook_dir` in a JupyterHub configuration file: https://github.com/jupyterhub/dockerspawner#data-persistence-and-dockerspawner. I think the same approach will work for `default_url` which is a traitlet on the base Spawner class, just like `notebook_dir`: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L388. I think the `base_url` is a traitlet of the JupyterHub class itself, and can be configured via a config file option in a similar manner: https://jupyterhub.readthedocs.io/en/stable/api/app.html?highlight=base_url

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
