### ISSUE TITLE
Permission denied when using Jupyterhub

### ISSUE THREAD

**Issue by vishwesh5** [jupyter/docker-stacks#695]
Hi!
This is very similar to https://github.com/jupyter/docker-stacks/issues/114 but the difference is that I am using **Zero-to-Jupyterhub** kubernetes google engine. Starting off, I prepared my own [dockerfile](https://github.com/vishwesh5/OpenCV-Docker/blob/master/Dockerfile-jupyter) which works fine in that I am able to launch the hub and access it through kubernetes. But, there are the following 2 issues:
1. I am logging in using a test user (random credentials) and when it logs in, it opens the `/opt/` directory.
2. When I try to create a new notebook in that directory, it says `Permission denied`. 
Can someone please help me out with this?
**What docker image you are using?**

Example: `jupyter/minimal-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I am using Zero-to-jupyterhub for this.

**What do you expect to happen?**

Since the dockerfile closes at `WORKDIR $HOME`, I expect to enter the home directory of the user. Since the new users are added, it should be an empty directory.

**What actually happens?**

The `/opt/` directory is opened and when I try to create a new notebook file in it, it says `permission denied`.

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience using Zero-to-JupyterHub and these images together can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
