### ISSUE TITLE
Failed to mount webdav in base-notebook container

### ISSUE THREAD

**Issue by SofianeB** [jupyter/docker-stacks#697]
**What docker image you are using?**

`jupyter/base-notebook` 

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Spawned automatically from jupyterhub

**What steps do you take once the container is running to reproduce the issue?**

```docker exec -it "container" bash mount -t davfs ...```

**What do you expect to happen?**

Create a directory in ~/work and mount webdav on it.

**What actually happens?**

Error

mount.davfs: no entry for ```https://XXXXX/remote.php/webdav/``` found in ```/etc/fstab```

The container is run with user ```jovyan``` but I can run ```mount.davfs``` without sudo.

Any help?

Thank you.

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in webdav + JupyterHub + Docker can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
