### ISSUE TITLE
Accessing MongoDB from within  the python app inside the container

### ISSUE THREAD

**Issue by pparchure** [jupyter/docker-stacks#698]
Hello Sir,
I am new to docker. I am using the jupyter-pyspark notebook to dockerize my application. I don't know how to access the mongodb DB which is on my host machine from inside my python app inside the container. It would be great if you could help me with this. 

Thanks

**Comment by bobmayuze** [comment]
I'm assuming you are running jupyter and MongoDB in the same container and have the following sturcture:
```
Your desktop/laptop 
  container
    jupyter
    mongo
```
Normally this is not really recommended, but I think you could change the bind ip setting in mongo.

The better way to do this is separating the mongo and jupyter into 2 containers with docker-compose. I have a sample [here](https://github.com/bobmayuze/django-celery-practice/blob/master/scripts/docker-compose.yml) you could be using.

**Comment by parente** [comment]
I'm going to close this issue since it's been inactive for some time. @bobmayuze 's link does provide a reasonable example of how docker-compose can help run services in separate containers. It can be adapted to run Jupyter Notebook in one and MongoDB in another. If MongoDB does need to be running on the host, using `--net host` on the Docker command line for starting the Jupyter container should also allow notebooks to access the DB.

In either case, be sure to read the Docker docs about the ramifications of containerizing all of your services, using host networking, etc.
