### ISSUE TITLE
How to use jupyter/pyspark-notebook  connect remote spark standalone cluster?

### ISSUE THREAD

**Issue by eromoe** [jupyter/docker-stacks#699]
**What docker image you are using?**

Example: ` jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I want something like below
Example: `docker run -it --rm -p 8889:8888 jupyter/pyspark-notebook:latest --sparkurl=spark://P-HS-1:7077,P-HS-2:7077`

But there is no document about how to use this image

**Comment by parente** [comment]
@eromoe a community member contributed documentation about how to connect the Spark images maintained here to a Spark Cluster running in standalone mode some time ago: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#connecting-to-a-spark-cluster-in-standalone-mode.

I do not know if they've kept pace with the changes to the images over time. We'd welcome pull requests to improve the docs in this area from you or others knowledgeable about running Spark in standalone mode.

**Comment by yusuf-nathani** [comment]
Hi @eromoe  - Did you get correct command to connect remote spark with docker image jupyter/pyspark-notebook ?
In my case I want to connect jupyter notebook to AWS Glue instance. Appreciate your tips.

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in using these images plus Spark standalone mode can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue. If someone with a working setup cares to update the recipe with more details, I'll gladly review a PR.
