### ISSUE TITLE
JupyterHub and DockerSpawner 

### ISSUE THREAD

**Issue by statiksof** [jupyter/docker-stacks#713]
**What docker image you are using?**
```jupyter/base-notebook```

**What complete docker command do you run to launch the container (omitting sensitive values)?**

using ```DockerSpawner```

**Question**

the ```Dockerfile``` includes installing ```JupyterHub``` and ```JupyterLab```.
Is this necessary when using DockerSpawner?

Thank you.

**Comment by minrk** [comment]
It is necessary to have the `jupyterhub` package in the image. This is already present in `jupyter/base-notebook`, so you don't need a custom image if you are using that one.

**Comment by statiksof** [comment]
Thanks @minrk get it. 
Please can you check why this configuration is not working. With this only one profile is selected.


```
c.JupyterHub.spawner_class = 'wrapspawner.ProfilesSpawner'

c.ProfilesSpawner.profiles = [
       ('Profile1', 'dockeruser', 'dockeruser', 'dockerspawner.DockerSpawner', dict(container_image="image1", remove_containers=True)),
       ('Profile2', 'dockeruser', 'dockerspawner.DockerSpawner', dict(container_image="image2", environment = { 'JUPYTER_ENABLE_LAB': 'yes' })),
 ]
```

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
