### ISSUE TITLE
Container Error: exit code 137

### ISSUE THREAD

**Issue by xieydd** [jupyter/docker-stacks#736]
Hi! Thanks for using the Jupyter Docker Stacks.

If you are looking to contribute to the images, please see the [Contributor's Guide] (http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

 ` jupyter/tensorflow-notebook:latest`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

 `/opt/conda/bin/jupyter notebook`

**What steps do you take once the container is running to reproduce the issue?**

**What do you expect to happen?**

Example: notebook server will keep working

**What actually happens?**

When i use Jupyter notebook in kubernetes container , the server will work few time(3 times in 3h), and the will exit .
This is the log 
```
jupyternotebook-xyd-847ff4564c-gqvn6   1/1       Running   3          3h        1/1
command terminated with exit code 137
```
Anybody help me?
@ericdill  @nbonnotte @parente

**Comment by ericdill** [comment]
Hi @xieydd,

With Kube there can be a number of places that need probing before we understand the root cause. Some questions to help get us going:

1. What is your pod config? You can find this by running `kubebctl describe po jupyternotebook-xyd-847ff4564c-gqvn6` and `kubectl get pod jupyternotebook-xyd-847ff4564c-gqvn6`
2. How are you running this pod? Do you have a deployment? Can you show the output of `kubectl get deploy`?
3. Can you attach the logs for your failed pod? `kubectl logs jupyternotebook-xyd-847ff4564c-gqvn6`

Finally, Exit code 137 suggests that you are experiencing an OOM kill. You might try to increase the amount of RAM available to your tensorflow notebook.

**Comment by xieydd** [comment]
Hi @ericdill 
Thank you for giving me inspiration；i check my yaml file,i have a mistake
```
command:
   - sleep
   - "3600"
```
I may be 3600d

**Comment by ericdill** [comment]
Great! Good luck 😀
