### ISSUE TITLE
vim not installed in minimal-notebook but is mentioned in documentation

### ISSUE THREAD

**Issue by wjgeorge** [jupyter/docker-stacks#779]
**What docker image you are using?**
jupyter/minimal-notebook

**What steps do you take once the container is running to reproduce the issue?**
create a notebook terminal and run vim.

**What do you expect to happen?**
vim is started

**What actually happens?**
vim is not found

**Comment by wjgeorge** [comment]
is this just an error in the documentation?

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-minimal-notebook

**Comment by peterprescott** [comment]
surely the fix needed here is to add vim to the Dockerfile for the minimal notebook, rather than to remove it from the docs? developers might be split into rival camps by their choice of minimal text editor, but the jupyter project surely aims to bridge those divides rather than pick sides? i'll go ahead and make the relevant PR...
