### ISSUE TITLE
Trying to install Java

### ISSUE THREAD

**Issue by aruizga7** [jupyter/docker-stacks#79]
Hi, I am trying to install Java but I have problem with root permission. Any idea about how to solve this?
![root](https://cloud.githubusercontent.com/assets/3798276/11700697/f469534c-9e90-11e5-9157-e566d7856a3d.PNG)

**Comment by parente** [comment]
In general, the README for the stack you're running about how to grant the `jovyan` user sudo. It's an environment variable `GRANT_SUDO` you have to set on `docker run`.

But since you're using the quick trick we doc'ed over here (https://github.com/jupyter-incubator/dashboards/issues/152#issuecomment-163388702), the container is not starting as root, the start-notebook script is not running, and so jovyan won't wind up with sudo even if you set the env var.

The right way to do this is really to build a new docker image with the libs you want preinstalled like:

```dockerfile
FROM jupyter/datascience-notebook
USER jovyan
RUN pip install jupyter_dashboards
USER root
RUN apt-get install openjdk-7-jdk
```

Then run it like:

```
docker build -t my/dashboard-notebook .
docker run -d -e GRANT_SUDO=yes -p 8888:8888 my/dashboard-notebook
```

The `GRANT_SUDO` is only need if you still plan to need / use sudo in the container after starting it (e.g., to configure additional libraries).

**Comment by aruizga7** [comment]
Thanks @parente You're everywhere ;-)

I am forking and making these changes then in the libs. Thanks!

**Comment by parente** [comment]
Occupational hazard? :)

No need to fork to git repos. Just write a new Dockerfile like the one above. The `jupyter/datascience-notebook` is maintained on Docker Hub. You can just inherit FROM it and install what you need. The benefit is that when the base image updates due to other pull requests here, you can rebuild easily.

**Comment by parente** [comment]
@aruizga7 did you get it installed? If so, we can close this.

**Comment by parente** [comment]
Closing. Can reopen if this is still a problem.
