### ISSUE TITLE
Make Spark on Kubernetes entrypoint script work with jupyter/*spark-notebook

### ISSUE THREAD

**Issue by pmkc** [jupyter/docker-stacks#797]
This is mostly a bug on Spark which I filed [here](https://issues.apache.org/jira/browse/SPARK-26597), but a few choices here break it futher

**What docker image you are using?**

Example: `jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`kubectl run --image jupyter/all-spark-notebook jupyter --port 8001 --expose`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Login to Jupyter
1. Create a Python notebook
1. Configure a SparkContext to run on kubernetes
1. Set the container image to jupyter/all-spark-notebook
  1. Note until [SPARK-26597](https://issues.apache.org/jira/browse/SPARK-26597) is resolved, I actually set it to a child image with the endpoint overridden to `["/usr/local/spark/kubernetes/dockerfiles/spark/entrypoint.sh"]`.
  1. This is definitely on them and not you.
1. Perform a computation in Spark

**What do you expect to happen?**

Spark schedules executors on Kubernetes and performs the computation.

**What actually happens?**

The executor script crashes because it assumes JAVA_HOME is set, assumes the path of tini is /sbin and uses the tini -s flag.

**Should jupyter/docker-stacks fix any of that?**
I'm not sure. I wanted to file this to document the issue and use case regardless.

Installing tini from Conda is unusual, I might file a bug on https://github.com/conda-forge/tini-feedstock to support the -s sub-reaping flag.

I've seen other users mention Spark on Kubernetes so if this is user error please correct me.

**Comment by ericdill** [comment]
I have little to add to your core issue here but I'd encourage you to engage @jakirkham over on the conda-forge feedstock (That's the maintainer of the feedstock). He's generally pretty overloaded already like all open-source maintainers, so no promise of an answer 😁 , but I'm sure he'd appreciate the input

**Comment by parente** [comment]
@pmkc We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience on this topic can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
