### ISSUE TITLE
Using "Accelerated Python" by Intel 

### ISSUE THREAD

**Issue by dirkcgrunwald** [jupyter/docker-stacks#809]
Intel has released a Python conda channel that uses their Intel-tuned accelerated libraries. They claim up to 20x performance improvements over the base Ubuntu numpy performance (see https://software.intel.com/en-us/distribution-for-python/benchmarks )

You can find more information at https://goo.gl/P1VMGX

My question was: has anyone successfully integrated this into docker-stacks? I tried prepending their channel to the Conda distribution in the base stack but some of the explicit version dependencies cause there to be a mix of Intel and conda-forge components.

**Comment by parente** [comment]
Hi @dirkcgrunwald. We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue since it has been idle for some time now.
