### ISSUE TITLE
Enabling man pages in containers

### ISSUE THREAD

**Issue by vilhelmen** [jupyter/docker-stacks#813]
Most OS container images blacklist the man pages for space reasons, but this can be pretty jarring when working in a notebook container terminal. Would it be worthwhile to re-enable the man pages in the images? It's as easy as adding the following to the base image (or a whole new image):

```dockerfile
# If it hasn't been set yet
ENV DEBIAN_FRONTEND noninteractive
USER root

RUN rm /etc/dpkg/dpkg.cfg.d/excludes \
	&& apt-get update \
    && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -yq --no-install-recommends --reinstall man \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
```
(This causes some package upgrades as the installed package versions no longer exist(!!), I would expect that list of upgrades to grow over time)

and then to wiggle around a man-db bug ([fixed in master but not released](https://git.savannah.gnu.org/cgit/man-db.git/commit/?id=8197d7824f814c5d4b992b4c8730b5b0f7ec589a), but who knows if Bionic will ever see it), do the following for Conda's multiple manpaths:

```dockerfile
USER root

RUN echo "MANPATH_MAP ${CONDA_DIR}/bin ${CONDA_DIR}/man" >> /etc/manpath.config \
	&& echo "MANPATH_MAP ${CONDA_DIR}/bin ${CONDA_DIR}/share/man" >> /etc/manpath.config \
	&& mandb
```

Looking at our containers, this balloons the Bionic image from 86MB to about 220MB (including our installation of `less tmux zip jq vim screen rsync htop`). This ballooning should stop at minimal since everything else is mostly done through conda. Our minimal container appears to be 3.08GB, with datascience coming in at 6.04GB.

Is this something we'd be interested in rolling into the main images, or left as a patch in some docs due to space concerns?

[(brought over from z2jh)](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1124)

**Comment by parente** [comment]
A guess a question is where to insert it into the tree of images. Adding it to base makes it available in all other images, but base is meant to be a reasonably constrained image without all the bells and whistles for actual use (e.g., no pandoc). minimal-notebook might be a better spot.

Or we can add the few lines to the docs as a recipe like you suggest. I'm on the fence and waiting to see if others have an opinion.

**Comment by vilhelmen** [comment]
That's a good point about base. I'd just be wary about putting it too far in the process since you have to reinstall every package. The reinstall can really eat up a lot bandwidth and time. I don't recall the number of dependencies brought in by base's package install, but running it first in minimal might be ok.

I originally had it as part of our final presentation layer applied on top of the stacks containers and man that was a **terrible** idea. If we add it to the docs, we may want to present it as a modification on the ubuntu source image to go before base, but then that means they have to go through the entire build process. I have that all automated, but that might be a big pain for end users. Putting it last can really try your patience, though. Especially if you're using multiple images!

**Comment by javabrett** [comment]
-1 for unconditionally adding man pages to any base, intermediate or final stacks image.

I prefer the alternate suggestion - diligently document the recipe and add to the documentation, so anyone making a derived image could easily install man-pages if-desired.  Or if that is insufficient, provide the recipe as an (unreferenced by-default) build-time script that could be called for a derived image.

**Comment by parente** [comment]
Let's start with documenting man page additions as a recipe. If there's overwhelming interest and support for making it a standard part of the build, with a recognition of the cost it brings, we can continue the conversation and figure out a next step.

@vilhelmen If you're still interested, feel free to send a recipe page PR for me to review.

**Comment by consideRatio** [comment]
I attempted to summarize some numbers @vilhelmen wrote in https://github.com/jupyter/docker-stacks/pull/837#issuecomment-478706819.

Image | Normal | Man early inject | Man late inject (bad idea) | Normal -> Early diff
-|-|-|-|-
ubuntu | 80 MB | - | 160 MB | 101%
base | 767 MB | 822 MB | 871 MB | 7%
minimal | 2747 MB | 2876 MB | 4903 MB | 5%
datascience | 5851 MB | 5854 MB | 8226 MB | 0.05%

1. I think it could make sense to have this included and customizable by a flag within the base-notebook Dockerfile.

2. I would cast a vote to enable it by default because I think most of our users are using notebooks built on top of base and minimal rather than those themselves. I'll look at docker hub's downloads to verify this. I sorted the list below based on course download numbers followed by Docker Hub stars. The base notebook wasn't very popular so the question is really if we can accept the 5% size hit on minimal in my view.

   Image|Downloads|Docker Hub stars
   -|-|-
   datascience-notebook|1M+|464
   all-spark-notebook|1M+|230
   scipy-notebook|1M+|162
   tensorflow-notebook|500K+|131
   minimal-notebook|500K+|76
   pyspark-notebook|100K+|101
   base-notebook|100K+|62
   r-notebook|50K+|22

**Comment by mathbunnyru** [comment]
I don't see a lot of activity here.
@vilhelmen please, if this topic is a lot of interest to you, create a PR where you enable man pages or reopen the issue.
Until then, I'm closing this issue.
