### ISSUE TITLE
is that possible to install jupyterlab-git in  jupyter/base-notebook/dockerfile?

### ISSUE THREAD

**Issue by roccqqck** [jupyter/docker-stacks#847]
sorry its not a issue
but i have to ask

almost every jupyter docker build FROM base-notebook

is that possible to install jupyterlab-git in  jupyter/base-notebook/dockerfile

that would be helpful

**Comment by parente** [comment]
We try to keep the base-notebook image free from extensions so that it can serve as a starting point for a variety of other images. We'd welcome a [recipe in the docs](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html) like the following showing how to add the JupyterLab git extension to a custom Dockerfile:

```
FROM jupyter/base-notebook
RUN jupyter labextension install @jupyterlab/git@^0.5.0 && \
    npm cache clean --force && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging
```

Would you like to send a PR?

**Comment by mathbunnyru** [comment]
I think the installation process is quite well documented and the best thing to do here is to create a docker images base on base-notebook and install extension on top of it:
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#conda-environments
https://github.com/jupyterlab/jupyterlab-git#install

Closing this one, as this seems to be pretty old issue.
