### ISSUE TITLE
add scikit-monaco package

### ISSUE THREAD

**Issue by daviddoji** [jupyter/docker-stacks#887]
From PyPi "scikit-monaco is a library for Monte Carlo integration in python".

It would be nice to have it included in the scipy-image.

**Comment by parente** [comment]
We prefer adding [recipes in the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html) over installing new packages in the images to avoid forever increasing the size of the docker images and maintenance burden of this repository. We'd be happy to review and merge a [recipe pull request](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html) for your library if you'd like to submit one.

**Comment by mathbunnyru** [comment]
Just cleaning up old issues, which haven't received response or outdated.

`scikit-monaco` is an outdated package (last commit was on 22 Feb 2018).
I think you won't be able to use it with latest docker stacks with recent python version (https://github.com/scikit-monaco/scikit-monaco/issues/14)

So, I'm going to close this issue. I also added `Upstream` label, because the upstream package is quite old and doesn't seem to work anymore.
