### ISSUE TITLE
Conflicting dependencies with jupyterlab-manager@1.0.2

### ISSUE THREAD

**Issue by wigging** [jupyter/docker-stacks#919]
I am trying to build the [docker-stacks/scipy-notebook/Dockerfile](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile) on my laptop but I get several errors related to JupyterLab. Below are the steps I am performing:

**Build the image**

```
# Copy the scipy-notebook Dockerfile to my local machine
# Then run the following command from within the folder containing the Dockerfile
docker build -t myimage .
```

**Errors from the Docker build**

```
Errored, use --debug for full output:
ValueError:
"@jupyter-widgets/jupyterlab-manager@1.0.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/application
>=2.2.1 <3.0.0          >=3.0.0 <4.0.0   @jupyterlab/coreutils
>=0.19.2 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/notebook
>=0.19.1 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/rendermime
>=3.2.1 <4.0.0          >=4.0.0 <5.0.0   @jupyterlab/services
```

**Comment by parente** [comment]
Each image starts `FROM` the latest parent image available on your local machine (https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile#L3). Docker doesn't refresh the latest parent image during a docker build.

Try:

```
docker pull jupyter/minimal-notebook:latest   # the parent image of scipy-notebook
docker build -t myimage .
```

Keep in mind that some of the Dockerfiles in this repo have dependencies on local files. I suggest cloning this repo, and using the included Makefile to build the images you need instead of downloading individual Dockerfiles.

**Comment by wigging** [comment]
Updating to the latest minimal-notebook image fixed the dependency issues. Thank you for the help.
