### ISSUE TITLE
after image built it did not delete the scipy image

### ISSUE THREAD

**Issue by skw1990** [jupyter/docker-stacks#932]
**What docker image you are using?**

Example: `jupyter/tensorflow-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

 `docker run -d -p 8889:8888 jupyter/tensorflow-notebook:`

**What do you expect to happen?**

Dependency image (scipy is deleted) when building image locally, i.e.: same result as docker pull jupyter/tensorflow-notebook

**What actually happens?**

scipy notebook still exists and eating out space.

**Comment by kronenpj** [comment]
TL;DR; It's a feature of docker with images inheriting from other images.

It stems from the way that `jupyter/tensorflow-notebook` inherits all the layers from `jupyter/scipy-notebook`. 

E.g. when I `docker pull jupyter/scipy-notebook`, with no existing layers, I pull down the entire set of layers (~3.5GB worth). If, after that action, I execute `docker pull jupyter/minimal-notebook` it pulls down zero layers because they're all part of the `jupyter/scipy-notebook` image I requested earlier.

**Comment by parente** [comment]
I believe this issue has been addressed by @kronenpj's answer. Since the issue has been inactive for some time now I'm going to close it.
