### ISSUE TITLE
how can i run  jupyter/all-spark-notebook  to existing Spark/mesos/hadoop  cluster ?

### ISSUE THREAD

**Issue by mudinet** [jupyter/docker-stacks#996]
Hi! Thanks for using the Jupyter Docker Stacks.

Please review the following guidance about how to ask questions, contribute changes, or report bugs in the Docker images maintained here.

1. If you have a general question about using these Docker images or with Jupyter + Docker in general, please post your question in the [Jupyter Discourse Q&A section](https://discourse.jupyter.org/c/questions) so that it can be seen, discussed, and hopefully answered by the community.

2. If you are looking to contribute to the images, please see the [Contributor's Guide](http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

3. If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Start an R notebook
3. ...

**What do you expect to happen?**

Example: ggplot output appears in my notebook.

**What actually happens?**

Example: No output is visible in the notebook and the notebook server log contains messages about ...

**Comment by romainx** [comment]
Hello,

There is [an entry](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#use-jupyter-all-spark-notebooks-with-an-existing-spark-yarn-cluster) on the documentation about this setup. However it will not be easy since we will have to use the same versions of Spark and Python to make it work. See #945 for an example of the issues you may face.

I think one of the best way to achieve this goal is to use a setup less dependent on Spark and Python libraries compatibility. This is the purpose of installing [Livy](https://livy.incubator.apache.org/) to provide an HTTP REST API in front of the cluster in order to submit Spark job. In this setup the driver runs on the cluster and so there is no compatibility issues between the driver and the cluster. 
However in this case it's not a true interactive mode you will have to query the Livy server to get the job status. Hopefully [Sparkmagic](https://github.com/jupyter-incubator/sparkmagic) is here to make your life easier and to emulate an interactive Spark session. See the PR #974 
for information about Sparkmagic.

Best

**Comment by romainx** [comment]
Hello,

We have no feedback since our answer and mesos support has been recently removed from the stack #911. Following this PR we have updated [the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html) #1098 to indicate how to use Spark, so you may find some information in this page.

So I'm closing this issue.
Best.

**Comment by OneCricketeer** [comment]
Related - https://stackoverflow.com/questions/45489248/running-spark-driver-program-in-docker-container-no-connection-back-from-execu/56486271#56486271
